Ocaml effects [parser]
Kakadu/fp2021 pull request #14
Opened 2021-12-07 19:52 UTC by qsqnk

2021-12-07 22:39 UTC, Kakadu commented on OCamlEff/lib/eval.ml
> +          new_res)
:)

2021-12-07 22:42 UTC, Kakadu commented on OCamlEff/lib/ast.ml
> +  | EPerform of effect * exp (*    perform (Choice x)   *)
А можно в камле с эффектами писать 
``` 
match ... with 
| effect x -> perform x
```
?

2021-12-07 22:43 UTC, zishkaz commented on OCamlEff/lib/eval.ml
> +          new_res)
Тут все пока грязновато, цель была заставить работать

2021-12-07 22:45 UTC, zishkaz commented on OCamlEff/lib/ast.ml
> +  | EPerform of effect * exp (*    perform (Choice x)   *)
У нас perform должен быть внутри выражение которое пытаемся сматчить чтобы хендлер сработал, поэтому нельзя

2021-12-07 22:56 UTC, Kakadu commented on OCamlEff/lib/typing.ml
> +      | CString _ -> return (Subst.empty, TString))
Вложенный pattern matching тут не будет лучше?

2021-12-07 22:58 UTC, Kakadu commented on OCamlEff/lib/typing.ml
> +        let* s_bool = unify t TInt in
Опечатка?

2021-12-07 22:59 UTC, Kakadu commented on OCamlEff/lib/typing.ml
> +      return (subst, tyexp)
Можно и покороче. Законы монад вспомните.

2021-12-07 22:59 UTC, zishkaz commented on OCamlEff/lib/typing.ml
> +      | CString _ -> return (Subst.empty, TString))
Лучше, не додумался сходу так сделать

2021-12-07 22:59 UTC, zishkaz commented on OCamlEff/lib/typing.ml
> +        let* s_bool = unify t TInt in
Верно, копипаста творит зло

2021-12-08 06:45 UTC, Kakadu commented on OCamlEff/lib/ast.ml
> +  | EPerform of effect * exp (*    perform (Choice x)   *)
Почему?

2021-12-08 12:32 UTC, zishkaz commented on OCamlEff/lib/ast.ml
> +  | EPerform of effect * exp (*    perform (Choice x)   *)
Вообще да, эта запись валидна. В моей реализации это может иметь смысл в контексте того что это матч хендлера и последующий перформ, но при этом должен быть хендлер поверх всего выражения паттерн матчинга, который словит этот перформ. В свою очередь, уже имеющийся хендлер словит перформ в выражении, которое пытаемся сматчить. Если же вы имели в виду матчинг самой сущности эффекта, то такое действие не подразумевалось и, возможно, зря. Конкретно про эффекты в окамл пока мало информации ибо они пока даже не релизнулись, поэтому делалось так чтобы соответствует функциональности, которую смогли вычленить из найденных источников.

2021-12-08 14:21 UTC, Kakadu commented
Ну вы догадались сделать `opam switch create ocaml-variants.4.12.0+domains+effects`?

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
On Wednesday, December 8th, 2021 at 3:32 PM, zishkaz ***@***.***> wrote:

> @zishkaz commented on this pull request.
>
> ---------------------------------------------------------------
>
> In [OCamlEff/lib/ast.ml](https://github.com/Kakadu/fp2021/pull/14#discussion_r764824019):
>
>> +and case = pat * exp (*  | _ :: [] -> 5  *) [@@deriving show { with_path = false }]
> +
> +and exp =
> +  | EConst of const (*    true    *)
> +  | EOp of infix_op * exp * exp (*    1 / (2 + 3)    *)
> +  | EUnOp of unary_op * exp (*    not predicate    *)
> +  | EVar of ident (*    x    *)
> +  | EList of exp list (*    [x; y; z]    *)
> +  | ETuple of exp list (*    x, y, z    *)
> +  | ECons of exp * exp (*    x :: xs    *)
> +  | EIf of exp * exp * exp (*    if predicate then x else y    *)
> +  | ELet of binding list * exp (*    let x = 5 in 10    *)
> +  | EFun of pat * exp (*    fun x,y,z -> x + y * z    *)
> +  | EApp of exp * exp (*    fold f list init    *)
> +  | EMatch of exp * case list (*    match lst with [] -> 0 | hd :: tl -> hd    *)
> +  | EPerform of effect * exp (*    perform (Choice x)   *)
>
> Вообще да, эта запись валидна. В моей реализации это может иметь смысл в контексте того что это матч хендлера и последующий перформ, но при этом должен быть хендлер поверх всего выражения паттерн матчинга, который словит этот перформ. В свою очередь, уже имеющийся хендлер словит перформ в выражении, которое пытаемся сматчить. Если же вы имели в виду матчинг самой сущности эффекта, то такое действие не подразумевалось и, возможно, зря. Конкретно про эффекты в окамл пока мало информации ибо они пока даже не релизнулись, поэтому делалось так чтобы соответствует функциональности, которую смогли вычленить из найденных источников.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, [view it on GitHub](https://github.com/Kakadu/fp2021/pull/14#discussion_r764824019), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/AADK7UUY43OD73PKLB36FQDUP5F6BANCNFSM5JSCJ2VQ).

2021-12-29 07:44 UTC, Kakadu commented on OCamlEff/lib/typing.ml
> +(***  я тут если чо*)
))))

2021-12-30 18:21 UTC, Kakadu commented on OCamlEff/DONT_REMOVE_THIS_DIRECTORY.md
> +personal pet project.
Вы хоть читаете, что выкладываете?

2021-12-30 18:22 UTC, Kakadu commented on OCamlEff/README.md
> +- ...
README WTF
Файлик с лицензией где?

2021-12-30 18:23 UTC, Kakadu commented on OCamlEff/demos/doubleHandling.t
> +  val helper = <fun>
А он типчики не печатает?

2021-12-30 18:24 UTC, qsqnk commented on OCamlEff/demos/doubleHandling.t
> +  val helper = <fun>
Пока нет. Когда закончим работу над тайпчекером, будет печатать

2021-12-30 18:24 UTC, Kakadu commented on OCamlEff/demos/doubleHandling.t
> +  val helper = <fun>
А вообще вы не хотели сделать как тут https://github.com/Kakadu/fp2021/blob/master/Lambda/demos/parsingTests.t#L7
Чтобы вход и выход был обозрим вместе, потому что в одном файле?

2021-12-30 18:26 UTC, Kakadu commented on OCamlEff/demos/exceptionImitation.t
> +  val safe_list_hd = <fun>
Вы выхлоп сортируете что-ли? Жутко неудобно проверять....

2021-12-30 18:29 UTC, Kakadu commented on OCamlEff/lib/ast.ml
> +type capitalized_ident = string [@@deriving show { with_path = false }]
choice? почему choice?

2021-12-30 18:31 UTC, Kakadu commented on OCamlEff/lib/ast.ml
> +  | TEffect of tyexp (**  (int -> int) eff  *)
Разве эффект это тип? В моем мире нет. В Муравьёвском тоже не совсем так.

2021-12-30 18:36 UTC, Kakadu commented on OCamlEff/lib/ast.ml
> +  | PEffectH of pat * ident (** effect x k *)
Здесь что-то с типизацией не так. OCaml правда умеет хэндлить эффект, где в его аргументах хэндлится другой эффект?

2021-12-30 18:37 UTC, Kakadu commented on OCamlEff/lib/eval.ml
> +  let pp_vars printer = iter (fun k v -> printer k v)
Длинно!

2021-12-30 18:42 UTC, Kakadu commented on OCamlEff/lib/eval.ml
> +    | PEffectH (pat, _), Eff2V (name_exp, v) -> match_pat pat (Eff2V (name_exp, v))
А почему тут не вечная рекурсия?

2021-12-30 18:42 UTC, Kakadu commented on OCamlEff/lib/eval.ml
> +    | PEffectH (pat, _), Eff2V (name_exp, v) -> match_pat pat (Eff2V (name_exp, v))
ааааа

2021-12-30 18:43 UTC, Kakadu commented on OCamlEff/lib/eval.ml
> +    | PEffectH (pat1, _), EffH pat2 when pat1 = pat2 -> return []
Что-то я не понимаю, как это работает тут.

2021-12-30 18:43 UTC, Kakadu commented on OCamlEff/lib/eval.ml
> +  ;;
List.filter_map?

2021-12-30 18:45 UTC, Kakadu commented on OCamlEff/lib/eval.ml
> +      | Error _ -> fail (Undef_var x))
Забавно, как получается ненужное исключение, при интерпретации программы, которая протипизировалась)

2021-12-30 18:46 UTC, Kakadu commented on OCamlEff/lib/eval.ml
> +          | Error x -> fail x)))
Попробуйте копипасту убрать.

2021-12-30 18:56 UTC, qsqnk commented on OCamlEff/lib/ast.ml
> +  | TEffect of tyexp (**  (int -> int) eff  *)
Согласно статье https://arxiv.org/pdf/2104.00250.pdf (стр 6) это тип:  ```type 'a eff = ...```

2021-12-30 19:01 UTC, Kakadu commented on OCamlEff/lib/eval.ml
> +      | Error x -> fail x)
А в чем была мотивация делать это в монаде Result, а не в той, которую передали?

2021-12-30 19:17 UTC, Kakadu commented on OCamlEff/lib/typing.ml
> +        let* s_uni = unify t1 t2 in
Если t1 -- это тип элемента списка, а t2 -- тип самого списка, то нафиг их унифицировать?

2021-12-30 20:06 UTC, Kakadu commented on OCamlEff/lib/typing.ml
> +            then fail Occurs_check
Я чего-то не понял в каком смысле тут occurs check....

2021-12-30 20:36 UTC, zishkaz commented on OCamlEff/lib/ast.ml
> +  | PEffectH of pat * ident (** effect x k *)
У вас вопрос к PEffectH?

2021-12-30 20:41 UTC, zishkaz commented on OCamlEff/lib/eval.ml
> +    | PEffectH (pat1, _), EffH pat2 when pat1 = pat2 -> return []
строка 186 - паттерн эффекта с конструктором матчится к сущности эффекта с конструктором, у которого внутри лежит значение конструктора.
строка 187 - паттерн хендлера матчится к эффекту без конструктора.
строка 188 - паттерн хендлера матчится к эффекту с конструктором.
строка 189 - паттерн хендлера матчится к забавной сущности, которая 4 часа отроду. EffH отвечает за тот факт, что во время хендлинга эффекта не произошел continue (юзкейс - эксепшены). Тогда мы из хендлера вернем эту сущность, а она просто прямо сматчится с хендлером внутри ematch, вызовет его експ, и уже вернет из всего ematch результат експа хендлера

2021-12-30 20:43 UTC, zishkaz commented on OCamlEff/lib/eval.ml
> +      | Error _ -> fail (Undef_var x))
Тут это осталось чтобы паттерн матчинг был полный, конечно он по сути никогда не вызовется

2021-12-30 20:44 UTC, zishkaz commented on OCamlEff/lib/eval.ml
> +          | Error x -> fail x)))
вы просто постоянные матчи лесенкой?

2021-12-30 20:46 UTC, zishkaz commented on OCamlEff/lib/typing.ml
> +        let* s_uni = unify t1 t2 in
Не факт же, что они одного типа

2021-12-30 20:48 UTC, zishkaz commented on OCamlEff/lib/typing.ml
> +            then fail Occurs_check
В окамле это "Variable is bound several times in this matching", и я решил не вводить новый еррор, а просто сказать этим что "pattern occurs in the remaining part of the tuple" ~ occurs.

2021-12-30 20:51 UTC, zishkaz commented on OCamlEff/lib/eval.ml
> +  ;;
Да, поправлю

2021-12-30 20:52 UTC, zishkaz commented on OCamlEff/lib/ast.ml
> +type capitalized_ident = string [@@deriving show { with_path = false }]
Это пример, что этот тип подразумевает стринг с заглавной буквы

2021-12-30 23:04 UTC, qsqnk commented on OCamlEff/demos/doubleHandling.t
> +  val helper = <fun>
Сделано

2021-12-30 23:05 UTC, qsqnk commented on OCamlEff/DONT_REMOVE_THIS_DIRECTORY.md
> +personal pet project.
Удалено

2021-12-30 23:07 UTC, qsqnk commented on OCamlEff/demos/exceptionImitation.t
> +  val safe_list_hd = <fun>
Для печати использутся ```iter```, а он проходит по мапке в порядке возрастания ключей

2021-12-30 23:27 UTC, qsqnk commented on OCamlEff/README.md
> +- ...
Readme исправлен, добавлен файл с лицензией WTFPL

2021-12-30 23:30 UTC, qsqnk commented on OCamlEff/lib/eval.ml
> +  ;;
Исправлено

2021-12-30 23:46 UTC, qsqnk commented on OCamlEff/lib/eval.ml
> +  let pp_vars printer = iter (fun k v -> printer k v)
Удалено

2021-12-31 05:22 UTC, qsqnk commented on OCamlEff/lib/eval.ml
> +      | Error x -> fail x)
Переписал. Теперь реализация интерпретатора никак не завязана на монаде Result

2021-12-31 09:17 UTC, Kakadu commented on OCamlEff/lib/eval.ml
> +  | Not_single_continue of exp
Вообще это называется Multishot Continuation

И это нарочно сделано ошибкой интерпретации, а не тайпчекинга?

2021-12-31 09:19 UTC, Kakadu commented on OCamlEff/lib/ast.ml
> +type capitalized_ident = string [@@deriving show { with_path = false }]
А почему к этому приписана дока Choice?  И что тут выбирается?

2021-12-31 09:20 UTC, Kakadu commented on OCamlEff/demos/exceptionImitation.t
> +  val safe_list_hd = <fun>
Представьте, что камлёвый REPL вам тоже так же сортировал. Вам бы было больно?

2021-12-31 09:21 UTC, Kakadu commented on OCamlEff/lib/ast.ml
> +  | PEffectH of pat * ident (** effect x k *)
да

2021-12-31 09:23 UTC, Kakadu commented on OCamlEff/lib/ast.ml
> +  | TEffect of tyexp (**  (int -> int) eff  *)
Предположим. А параметр это что? И у вас правда будут работать функции с типом ` 'a eff -> 'a eff -> 'a eff` ?

2021-12-31 09:24 UTC, Kakadu commented on OCamlEff/lib/eval.ml
> +    | PEffectH (pat1, _), EffH pat2 when pat1 = pat2 -> return []
Я не очень понял. Что такое эффект без конструктора? Без аргумента я могу догадаться, но без конструктора....

2021-12-31 09:26 UTC, Kakadu commented on OCamlEff/lib/eval.ml
> +      | Error _ -> fail (Undef_var x))
Со стороны это выглядит, будто Вы содержательно беспокоитесь об это исключении. И поэжтому вызывает вопросы.

2021-12-31 09:26 UTC, Kakadu commented on OCamlEff/lib/typing.ml
> +        let* s_uni = unify t1 t2 in
А разве не факт, что они разного?

2021-12-31 09:27 UTC, Kakadu commented on OCamlEff/lib/typing.ml
> +            then fail Occurs_check
Но исключении сильно напоминает Occurs_check при унификации. Переименуйте как-нибудь

2021-12-31 09:28 UTC, Kakadu commented
И постарайтесь что-то с копипастой задетектированной сделать

2021-12-31 11:00 UTC, zishkaz commented on OCamlEff/lib/typing.ml
> +            then fail Occurs_check
Сделаю

2021-12-31 11:02 UTC, zishkaz commented on OCamlEff/lib/eval.ml
> +  | Not_single_continue of exp
Это сделано нарочно ибо так было наиболее удобно сделать, но вообще можно во время типизации ematch то же самое сделать. Подумаем насчёт этого

2022-01-01 18:31 UTC, qsqnk commented on OCamlEff/lib/ast.ml
> +  | TEffect of tyexp (**  (int -> int) eff  *)
Параметр у конструктора ```TEffect``` - это типовый параметр ```'a```.
 Насчет функций с типом ```'a eff -> 'a eff -> 'a eff```: что в свитче 4.12.0+domains+effects, что у нас, следующий код, где у функции ```f``` тип ```int eff -> int eff -> int eff```, выполняется.
 
 ```
 effect E : int ;;

  let f e1 e2 = match e1, e2 with 
  | E, E -> E
  | _ -> E;;

  let res = f E E;;
  ```

2022-01-01 19:14 UTC, qsqnk commented on OCamlEff/lib/ast.ml
> +type capitalized_ident = string [@@deriving show { with_path = false }]
Заменено регулярным выражением

2022-01-01 23:21 UTC, qsqnk commented on OCamlEff/demos/exceptionImitation.t
> +  val safe_list_hd = <fun>
Представил. Теперь принтит в порядке объявлений в коде

2022-01-03 11:44 UTC, zishkaz commented on OCamlEff/lib/eval.ml
> +    | PEffectH (pat1, _), EffH pat2 when pat1 = pat2 -> return []
Я имел в виду под этим эффект без аргумента. То есть чтобы сделать perform эффекта не потребуется передавать значение

2022-01-03 12:06 UTC, zishkaz commented on OCamlEff/lib/eval.ml
> +  | Not_single_continue of exp
сделал это ошибкой тайпчекинга

2022-01-03 12:06 UTC, zishkaz commented on OCamlEff/lib/typing.ml
> +            then fail Occurs_check
переименовал

2022-01-03 12:06 UTC, zishkaz commented on OCamlEff/lib/typing.ml
> +        let* s_uni = unify t1 t2 in
верно, убрал эту унификацию

2022-01-03 12:07 UTC, zishkaz commented on OCamlEff/lib/ast.ml
> +  | PEffectH of pat * ident (** effect x k *)
В данном случае это паттерн хендлера, поэтому в типе pat у PEffectH будет либо PEffect1, либо PEffect2. Не очень понимаю сути вопроса про типизацию

2022-01-03 12:44 UTC, Kakadu commented on OCamlEff/lib/ast.ml
> +  | TEffect of tyexp (**  (int -> int) eff  *)
Короче я подумал, и вроде это не так ужасно как показалось в начале. 
А можно ли передать эффект как аргумент в функцию и попытаться его поймать?

2022-01-03 13:15 UTC, Kakadu requested changes
Я там попробовал всё сломать и у меня вроде получилось. Или нет?

2022-01-03 17:06 UTC, qsqnk commented on OCamlEff/lib/eval.ml
> +let extend_env_map id x = EnvMap.add id x
Не нашел подходящего окошка для обсуждений закомиченных вами тестов, поэтому тут.

С тестами, где должен упасть тайпчекер, все в порядке: он падает. Просто тайпчекер пока не подключен и перед интерпретацией не проводилась проверка типов.

2022-01-03 19:18 UTC, Kakadu commented on OCamlEff/lib/eval.ml
> +let extend_env_map id x = EnvMap.add id x
OMFG!

2022-01-05 04:49 UTC, qsqnk commented on OCamlEff/lib/ast.ml
> +  | TEffect of tyexp (**  (int -> int) eff  *)
У нас такое не поддерживается.
В свитче тоже кидается ошибка ```Error: Effect patterns must be at the top level of a match case.``` на код
```
effect E : int;;

let f e = function 
  | effect e k -> continue k 0
  | res -> res;;
  ```

2022-01-05 06:50 UTC, qsqnk commented on OCamlEff/lib/eval.ml
> +  print_newline ()
Поправил

2022-01-05 15:08 UTC, Kakadu commented on OCamlEff/lib/typing.ml
>            let* s8, t8 = mega_helper ((pat2, exp2) :: tl) in
А что там была за история с не тейлреком?

2022-01-05 20:26 UTC, zishkaz commented on OCamlEff/lib/typing.ml
>            let* s8, t8 = mega_helper ((pat2, exp2) :: tl) in
Я просто не смог её сходу сделать тейлрек и спустя такое количество времени решил оставить как есть

2022-01-06 10:51 UTC, qsqnk commented on OCamlEff/lib/eval.ml
> +let extend_env_map id x = EnvMap.add id x
Добавил проверку типов перед интерпретацией. В cram тестах теперь печатается тип/возникшая ошибка при выводе типа. Также вновь добавил ваши тесты.

2022-01-06 11:55 UTC, Kakadu commented on OCamlEff/lib/typing.ml
>            let* s8, t8 = mega_helper ((pat2, exp2) :: tl) in
Я ж вроде рассказывал что да как, не?

2022-01-07 15:26 UTC, zishkaz commented on OCamlEff/lib/eval.ml
> +[@@deriving show { with_path = false }]
Добавлено

2022-01-07 15:26 UTC, zishkaz commented on OCamlEff/lib/typing.ml
> +  | Typing_failure_pat of pat
Добавлено

2022-01-07 15:54 UTC, qsqnk commented on OCamlEff/lib/ast.ml
> +  | PEffectH of pat * ident (** effect x k *)
Подумал и решил сделать это ошибкой тайпчекера: если в хэндлере лежит что-то ```PEffect1```, ```PEffect2```, то бросается ошибка ```Effect patterns must be at the top level of a match case.```

2022-01-07 16:38 UTC, zishkaz commented on OCamlEff/lib/typing.ml
>            let* s8, t8 = mega_helper ((pat2, exp2) :: tl) in
переписал это чудовище на нормальный, мужской фолд

2022-01-07 20:33 UTC, zishkaz commented on OCamlEff/lib/eval.ml
> +    | PEffectH (pat1, _), EffH pat2 when pat1 = pat2 -> return []
Сделано

2022-01-11 15:03 UTC, zishkaz commented
@Kakadu починили деление на ноль

2022-01-11 16:19 UTC, qsqnk commented
@Kakadu, полагаю, что при интерпретации кода 

```
let rec fib = fun x -> 1 :: (fib x);;
let _ = fib 1;;
```

бросается ```segmentation fault``` вместо ```stack overflow```, поскольку при интерпретации бесконечно вызывается ```eval_exp```, внутри которого вызывается external функция ```Lazy.force```. 

Что-то подобное описывается здесь https://discuss.ocaml.org/t/stack-overflow-reported-as-segfault/8646

2022-01-13 11:47 UTC, Kakadu commented
У меня жалуется на кофликты. Сделайте что-нибудь @zishkaz  @qsqnk

2022-01-13 11:54 UTC, Kakadu commented
Потом надо разобраться в каком виде у вас сделан stdlib. Желательно отдельным пулл-реквестом.

2022-01-13 11:54 UTC, Kakadu approved these changes

2022-01-13 12:10 UTC, merged