Bash
Kakadu/fp2021 pull request #15
Opened 2021-12-13 20:49 UTC by TimPushkin

Мини-Bash в процессе разработки

2021-12-13 21:00 UTC, TimPushkin commented
Пока есть AST и парсер со следующими оговорками:

**AST:**
- Думаю уменьшить число конструкторов, а то как-то размашисто
- В Bash простая команда не является compound, как у меня, но так как у меня нет  `{ ... }`, она там нужна для функций

**Парсер:**
- Изначально планировалась поддержка `[[ ... ]]`, но потом я понял, что оно скорее для работы с файловой системой, а обычные логические операции можно заменить пайпами с их отрицанием через `!` и листами с `&&` и `||`
- Нет поддержки кавычек, хотя изначально и планировалась. Можно ли оставить без них?
- Поддержка positional parameters не планировалась, но тогда функции будут без аргументов (к ним будет никак не обратиться), поэтому, видимо, придется вводить
- Как я и писал, нет поддержки вложенных expansion'ов, но все-таки сделал некоторые исключения, которые можно увидеть по AST (в частности, есть parameter expansion внутри arithmetic expansion, чтобы можно было вставлять переменные в арифметические выражения); в README пока это не описал

2021-12-13 21:36 UTC, TimPushkin commented
Пока не знаю, как добавить `ppx_deriving.show` в CI...

2021-12-15 10:39 UTC, TimPushkin commented
Ещё, пока не знаю, как организовать тесты: сейчас они в отдельном файле, но тогда, если я введу `.mli` интерфейс, то потеряю в них доступ к некоторым функциям из `.ml`. К примеру, для парсера я бы добавил в интерфейс лишь итоговую `parse` функцию, но тестирую я, естественно, далеко не только её

2021-12-15 11:16 UTC, Kakadu commented
> Ещё, пока не знаю, как организовать тесты: сейчас они в отдельном файле, но тогда, если я введу `.mli` интерфейс, то потеряю в них доступ к некоторым функциям из `.ml`. К примеру, для парсера я бы добавил в интерфейс лишь итоговую `parse` функцию, но тестирую я, естественно, далеко не только её

Мне ничего не мешает
https://github.com/Kakadu/fp2021/blob/master/Lambda/lib/parser.ml#L52

2021-12-15 11:19 UTC, Kakadu commented on Bash/lib/ast.ml
> +  | Substring of var * int * int (* ${name:offset[:length]} *)
У Вас документация только частично попадает в документацию
https://kakadu.github.io/fp2021/docs/Bash/Bash/Bash_lib/Ast/index.html#type-param_exp
Сделайте нормально

2021-12-15 11:21 UTC, Kakadu commented on Bash/lib/parser.ml
> +;;
Как вариант Вы можете долинковать расширение стандартной библиотеки `base` и вызывать какие-нибудь функции отттуда.

2021-12-15 11:24 UTC, Kakadu commented on Bash/lib/tests.ml
> +    false
По-моему просто printf было бы короче. Вам же про него на проге рассказывали?

2021-12-19 20:05 UTC, TimPushkin commented on Bash/lib/ast.ml
> +  | Substring of var * int * int (* ${name:offset[:length]} *)
Изначально думал оставить это как комментарии, но как документация оно действительно лучше. Исправил

2021-12-19 20:05 UTC, TimPushkin commented on Bash/lib/parser.ml
> +;;
Исправил

2021-12-19 20:05 UTC, TimPushkin commented on Bash/lib/tests.ml
> +    false
Рассказывали, исправил

2021-12-19 20:08 UTC, TimPushkin commented
> > Ещё, пока не знаю, как организовать тесты: сейчас они в отдельном файле, но тогда, если я введу `.mli` интерфейс, то потеряю в них доступ к некоторым функциям из `.ml`. К примеру, для парсера я бы добавил в интерфейс лишь итоговую `parse` функцию, но тестирую я, естественно, далеко не только её
> 
> Мне ничего не мешает https://github.com/Kakadu/fp2021/blob/master/Lambda/lib/parser.ml#L52

У вас по ссылке же тесты в том же `.ml` файле, а у меня в отдельном -- `tests.ml`. Просто если их писать прямо в файле парсера, то этот файл раздуется в два раза, так как тестов много, поэтому хотелось вынести. Можно теперь, когда парсер функционирует, многие убрать, но грустно их просто так затирать...

2021-12-19 20:40 UTC, Kakadu commented
> У вас по ссылке же тесты в том же `.ml` файле, а у меня в отдельном -- `tests.ml`. Просто если их писать прямо в файле парсера, то этот файл раздуется в два раза, так как тестов много, поэтому хотелось вынести. Можно теперь, когда парсер функционирует, многие убрать, но грустно их просто так затирать...

Как вариант можно экспортировать всё что нужно в приватный модуль библиотеки, тестировать, а потом из отдельного (головного) модуля библиотеки инклюдить парсер и показывать наружу только то, что нужно (приватный модуль окажется скрыт). Но это оверкилл для этого ДЗ, проблем с зачетом из-за супер раздутого тестами файла парсера у Вас не будет.

2022-01-03 13:32 UTC, Kakadu commented
Я так понимаю демок с исполнением пока нет?

2022-01-03 13:33 UTC, Kakadu commented on Bash/lib/ast.ml
> +  *)
Наверное это тоже кусок документации, не?

2022-01-03 13:34 UTC, Kakadu commented on Bash/lib/ast.ml
> +[@@deriving show { with_path = false }]
А в чем была мотивация завести отдельный тип, а не стандартный список?

2022-01-03 13:49 UTC, TimPushkin commented
> Я так понимаю демок с исполнением пока нет?

Пока делал демку с факториалом понял, что текущая грамматика не позволяет его реализовать (из-за отсутствия `{ ... }` в функции нельзя указывать несколько команд), поэтому сейчас переписываю AST, что тащит за собой изменения в парсере и интерпретаторе.

В общем, все работает, но чтобы этим можно было пользоваться, нужно сделать крупный рефакторинг всего, чем и занимаюсь.

2022-01-03 13:49 UTC, Kakadu approved these changes

2022-01-04 13:23 UTC, TimPushkin commented on Bash/lib/ast.ml
> +  *)
Исправил

2022-01-04 19:46 UTC, Kakadu requested changes

2022-01-04 19:46 UTC, Kakadu commented on Bash/demos/interpretTests.t
> +  >
А можете больше тестов в таком стиле сделать? А то там в списке баша было много мелких фич, было бы круто по одному тесту на фичу. А то те инлайн тесты что есть не очень удобные, они не выглядят как готовые примеры, да и порою тестят только парсер, а не парсер+интерпретатор вдвоем.

2022-01-04 19:46 UTC, Kakadu commented on Bash/lib/interpreter.ml
> +      Printf.printf "Stdout: \"%s\"\nStderr: \"%s\"\n" act_stdout act_stderr;
%S

2022-01-04 19:46 UTC, Kakadu commented on Bash/lib/interpreter.ml
> +  ;;
Попробуйте в 1 строчку написать

2022-01-05 09:51 UTC, TimPushkin commented on Bash/demos/interpretTests.t
> +  >
Сделал

2022-01-05 09:51 UTC, TimPushkin commented on Bash/lib/interpreter.ml
> +      Printf.printf "Stdout: \"%s\"\nStderr: \"%s\"\n" act_stdout act_stderr;
Исправил

2022-01-05 09:51 UTC, TimPushkin commented on Bash/lib/interpreter.ml
> +  ;;
Сделал

2022-01-05 14:57 UTC, Kakadu commented on Bash/demos/interpretTests.t
> +Pipeline lists: with && the left side is computated onlu if the left side is true, with
only

2022-01-05 15:00 UTC, Kakadu commented on Bash/lib/ast.ml
> +[@@deriving show { with_path = false }]
https://kakadu.github.io/fp2021/docs/Bash/Bash/Bash_lib/Ast/index.html
А фигурные скобки точно надо экранировать?

2022-01-05 16:16 UTC, TimPushkin commented on Bash/demos/interpretTests.t
> +Pipeline lists: with && the left side is computated onlu if the left side is true, with
Исправил

2022-01-05 16:17 UTC, TimPushkin commented on Bash/lib/ast.ml
> +[@@deriving show { with_path = false }]
[Документация](https://ocaml.org/manual/ocamldoc.html) говорит, что нужно. Для проверки убрал экранирование, но ожидаю, что они пропадут

2022-01-05 19:16 UTC, Kakadu commented on Bash/lib/ast.ml
> +[@@deriving show { with_path = false }]
Там по умолчанию https://github.com/ocaml/odoc используется

2022-01-05 19:20 UTC, Kakadu commented on Bash/demos/interpretTests.t
> +  >
точно? Там вроде длинный список был....

2022-01-05 19:21 UTC, Kakadu commented on Bash/lib/interpreter.ml
> +;;
У Вас в другом файле либа Stdio исползуется. С помощью неё нельзя ввод-вывод сделать? Или тут важно, что из дескриптора читается?

2022-01-05 20:49 UTC, TimPushkin commented on Bash/demos/interpretTests.t
> +  >
Добавил больше демок с перенаправлениями, а остальное вроде бы продемонстрировано

2022-01-05 20:50 UTC, TimPushkin commented on Bash/lib/interpreter.ml
> +;;
Заменил на использование Stdio с преобразованием дескриптора в канал. Сам дескриптор нужен для `Unix.pipe`

2022-01-07 11:56 UTC, TimPushkin commented on Bash/demos/interpretTests.t
> +  >
Добавил ещё больше демок -- теперь точно есть всё (кроме `[[ ... ]]`, потому что, как я описывал выше, логические операции в Bash делаются через пайпы и листы) и демки ко всему

2022-01-11 15:18 UTC, Kakadu commented
Из tasks.md
> * Надо будет сделать основную штуку, что отличает bash от всего остального -- вызов сторонних исполняемых файлов по ходу дела
>    * Чтобы Ctrl-C их сторонних файлов возвращался обратно в bash

Как мне это проверить?

2022-01-11 18:13 UTC, TimPushkin commented
> Из tasks.md
> 
> > * Надо будет сделать основную штуку, что отличает bash от всего остального -- вызов сторонних исполняемых файлов по ходу дела
> >   
> >   * Чтобы Ctrl-C их сторонних файлов возвращался обратно в bash
> 
> Как мне это проверить?

По вызову сторонних файлов демка уже была, про Ctrl-C предполагалось, что только вручную, но теперь на это тоже сделал демку

2022-01-12 07:36 UTC, Kakadu commented
> По вызову сторонних файлов демка уже была, про Ctrl-C предполагалось, что только вручную, но теперь на это тоже сделал демку

А в ручную это как?

2022-01-12 08:12 UTC, TimPushkin commented
> > По вызову сторонних файлов демка уже была, про Ctrl-C предполагалось, что только вручную, но теперь на это тоже сделал демку
> 
> А вручную это как?

Например, создать два скрипта: один с вечным циклом --он будет внешний, другой его вызывающий. Запустить второй, нажать Ctrl-C, увидеть, что из вечного цикла мы вышли. Но теперь это не нужно, так как реализовано в демке.

2022-01-12 10:01 UTC, Kakadu commented
> тором -- он уйдет в вечный цикл. Нажать Ctrl-C, увидеть, что из вечного цикла мы вышли. Но теперь это не требуется, так как именно оно и реализовано в демке.

А там есть какой-нить REPL, чтобы в нём запустить цикл и прожать Ctrl-C?

2022-01-12 10:39 UTC, TimPushkin commented
> > тором -- он уйдет в вечный цикл. Нажать Ctrl-C, увидеть, что из вечного цикла мы вышли. Но теперь это не требуется, так как именно оно и реализовано в демке.
> 
> А там есть какой-нить REPL, чтобы в нём запустить цикл и прожать Ctrl-C?

Нет, REPL нет

2022-01-12 13:11 UTC, Kakadu commented on Bash/demos/interpretTests.t
> +
Я что-то не понял, где тут автоматически Ctrl-C нажимается. А если не нажимается, то почему тест не зависает?

2022-01-12 13:21 UTC, TimPushkin commented on Bash/demos/interpretTests.t
> +
Само нажатие Ctrl-C происходит в `demoInterrupt.ml`: там скрипт запускается в форкнутом процессе, а основной ждёт, пока тот зайдет в вечный цикл (напечатает что-либо в `stderr`), и затем шлёт ему Ctrl-C сигнал.

2022-01-12 14:56 UTC, Kakadu commented on Bash/demos/interpretTests.t
> +
У меня нет уверенности, что там всё ОК. Сделайте REPL короче, чтобы можно было руками протестить. Или закодируйте это в .t файл на вашем баше (я не знаю как именно)

2022-01-13 08:57 UTC, TimPushkin commented on Bash/demos/interpretTests.t
> +
Сделал REPL

2022-01-13 11:21 UTC, Kakadu commented
Из tasks.md
> * Надо будет сделать основную штуку, что отличает bash от всего остального -- вызов **сторонних** исполняемых файлов по ходу дела
По-моему первый пункт условия всё ещё не сделан.

2022-01-13 11:36 UTC, TimPushkin commented
> Из tasks.md
> 
> > * Надо будет сделать основную штуку, что отличает bash от всего остального -- вызов **сторонних** исполняемых файлов по ходу дела
> 
> По-моему первый пункт условия всё ещё не сделан.

А что под этим подразумевалось? Я думал, что возможность написать скрипт в некотором файле и вызвать его из этого файла в другом скрипте -- это есть.

2022-01-13 20:47 UTC, TimPushkin commented
> Из tasks.md
> 
> > * Надо будет сделать основную штуку, что отличает bash от всего остального -- вызов **сторонних** исполняемых файлов по ходу дела
> 
> По-моему первый пункт условия всё ещё не сделан.

Реализовал вызов сторонних файлов следующим образом: сначала идет попытка интерпретировать файл моим интерпретатором, если она проваливается, то идет запуск через систему как внешнего исполнимого файла.

2022-01-13 21:06 UTC, Kakadu commented
Что-то я не понял как именно
```
➜  Bash git:(bash) ✗ dune build
➜  Bash git:(bash) ✗ rlwrap dune exec ./REPL.exe
        MiniBash REPL
- To run a command type it and press Enter
- To stop typing a multiline command prematurely, enter an empty line
- To exit REPL type `exit` or press Ctrl-D
$ find
find: command not found
return code: 127
$ 
```

2022-01-14 14:59 UTC, merged