OCaml with typed effects
Kakadu/fp2021 pull request #16
Opened 2021-12-25 20:44 UTC by IlyaMuravjov

Пока реализованы парсер и тайпчекер, планируется в ближайшее время доделать интерпретатор.

Поддерживаемые типы:

- Примитивы: `int`, `string` и `bool`
- Исключения: `Exc1` и `Exc2`
- Составные типы: `'a list`, `'a ref`, `'a -['e]-> 'b`, кортежи, включая `()` (a.k.a. `unit`)
- Типовые параметры

Поддерживаемые типы эффектов: `IO`, `Asgmt`, `exc Exc1`, `exc Exc1`, типовые параметры для эффектов.

Можно указывать несколько эффектов через запятую, например, `int -[exc Exc1, IO]-> int`.

От эффектов-исключений можно избавляться с помощью `try`, если обработчики исключений не прокидывают исключения.

Планируемые функции стандартной библиотеки (тайпчекер про них уже знает):

- `val println : string -[IO]-> unit` - вывод строки в `stdout`
- `val raise1 : unit -[exc Exc1]-> 'a` - бросание исключения `Exc1`
- `val raise2 : unit -[exc Exc2]-> 'a` - бросание исключения `Exc2`
- `val ref : 'a --> 'a ref` - создание ссылки, которую можно разыменовывать оператором `!` и изменять оператором `:=`, имеющим эффект `Asgmt`
- `val sneaky_eff : ('a -['e]-> 'b) --> 'a -['e2]-> 'b` - скрытие эффектов функции для определения, например, `debug_println = sneaky_eff println` (нужно только чтобы обманывать тайпчекер, для интерпретатора, вообще не знающего про эффекты, это обычное `id`)

У всех `let` и аргументов функций должен быть явно указан тип.

Неподдерживаемый синтаксический сахар:

- Wildcard `_` (заменим именованной переменной)
- Выражения верхнего уровня, кроме `let` (заменимы выражениями верхнего уровня, присеваемыми в переменные)
- `if ... then ... else`, `function`, destructuring declarations для `let` и аргументов функций (заменимы явным `match`)
- Создание списков с помощью `[a; b; c]` (заменимо `a :: b :: c :: []`)
- Функции нескольких переменных (заменимы функцией одной переменной, возвращающей функцию, например, `fun n : int -> fun m : int -> n + m`)
- Альтернативный синтаксис привязки функциональных значений к переменными с помощью `let` с дополнительными параметрами (заменим объявлением анонимной функции с помощью `fun` и привязкой её к переменной)

2021-12-26 10:52 UTC, Kakadu requested changes
Для начала неплохо. Но меня как-то смущает явное введение связанных и обычных переменных. Может как-то без этого?

2021-12-26 10:52 UTC, Kakadu commented on OCamlTyEff/lib/ast.ml
> +  | TBoundVar of string
Допишите доку, чем отличается это от предыдущего

2021-12-26 10:52 UTC, Kakadu commented on OCamlTyEff/lib/ast.ml
> +  | TBoundVar of string
В моем текущем понимании кода я не понимаю зачем это нужно.

2021-12-26 10:52 UTC, Kakadu commented on OCamlTyEff/lib/ast.ml
> +;;
Я думаю это всё можно написать покороче. Вы нарочно игнорируете наличие "%a"?

2021-12-26 10:52 UTC, Kakadu commented on OCamlTyEff/lib/ast.ml
> +let _or = Or
По канону подчерк если уж ставить, то в конец

2021-12-26 10:52 UTC, Kakadu commented on OCamlTyEff/lib/ast.ml
> +  | CString s -> fprintf fmt "\"%s\"" s
"%S"

2021-12-26 10:52 UTC, Kakadu commented on OCamlTyEff/lib/ast.ml
> +      (fun fmt eff -> pp_ptrn fmt eff)
Длинно как-то....

2021-12-26 10:52 UTC, Kakadu commented on OCamlTyEff/lib/parser.ml
> +  | "class"
Копипастили откуда-то?

2021-12-26 10:52 UTC, Kakadu commented on OCamlTyEff/lib/tychk.ml
> +;;
Вот Вы что-то подставляете для нормальных типлвых переменных, а потом для тех переменных, что в эффектах, причем 1й результат используется явно во втором. Складывается впечатление, что типовые переменные обычные и "эффектные" как-то могут пересекаться. Это действительно так?

2021-12-26 10:52 UTC, Kakadu commented on OCamlTyEff/lib/tychk.ml
> +         | _ -> List.to_seq [ eff ])
Seq.return?

2021-12-26 10:52 UTC, Kakadu commented on OCamlTyEff/lib/tychk.ml
> +;;
induce по канону это apply

2021-12-26 10:52 UTC, Kakadu commented on OCamlTyEff/lib/tychk.ml
> +;;
Seq.filter_map?

2021-12-26 10:52 UTC, Kakadu commented on OCamlTyEff/lib/tychk.ml
> +      TTuple tys, List.fold_left (fun e1 e2 -> EffSet.union e1 e2) EffSet.empty effss
Тут точно eta правило надо применять. Посмотрите в других местах тоже.
К сожалению я не могу это просто запихнуть в линтер, так как оно не всегда корректно

2021-12-26 10:52 UTC, Kakadu commented on OCamlTyEff/lib/tychk.ml
> +exception Empty_macth
опечатка

2021-12-26 10:52 UTC, Kakadu commented on OCamlTyEff/lib/tychk.ml
> +      | (ptrn1, case1) :: cases ->
Думаю, глубокий мэтчинг будет почитабельней.

2021-12-26 15:57 UTC, IlyaMuravjov commented on OCamlTyEff/lib/ast.ml
> +  | TBoundVar of string
Связанные типовые переменные нельзя унифицировать, так как считается что они уже с чем-то унифицированы.

Например, реализация `id : 'a --> 'a` не может вернуть `1`, унифицировав `'a` с `int`, поэтому внутри `id` типовая переменная `'a` связанная, а снаружи `id` можно вызвать `id 1`, унифицировав `'a` с `int`, поэтому снаружи `id` типовая переменная `'a` несвязанная (на самом деле снаружи `id` эту переименует и она будет называться уже не `'a`).

Таким образом, типовые переменные являются связанными тогда и только тогда, когда они встречались в типах параметров объемлющих их функций.

В принципе в `ty_chk_env` и так указано, какие типовые переменные сейчас связанные, поэтому вместо постоянной замены `TVar` на `TBoundVar` и обратно можно вообще убрать `TBoundVar` (и `EffBoundVar`) и передавать `ty_chk_env` во все функции, которым важна связанность типовых переменных, что я и сделал в новом коммите.

2021-12-26 16:05 UTC, IlyaMuravjov commented on OCamlTyEff/lib/tychk.ml
> +    (ELet
Понимаю. Руками эти деревья я и не писал -- их генерировал парсер, а я потом уже вручную проверял его вывод на соответствие вводу. Мотивация здесь такая: если сломать парсер, то тесты тайпчекера не должны перестать проходить. Но раз вы думаете, что здесь лучше запустить парсер, то я так и сделаю.

2021-12-26 16:07 UTC, IlyaMuravjov commented on OCamlTyEff/lib/tychk.ml
> +let rec deduce_subst prm_ty arg_ty subst =
Да, изначально планировалась немного другая семантика, но сейчас это обычная унификация. Переименую обратно.

2021-12-26 16:13 UTC, IlyaMuravjov commented on OCamlTyEff/lib/parser.ml
> +  | "class"
[Отсюда](https://ocaml.org/manual/lex.html#sss:keywords)

2021-12-26 16:28 UTC, IlyaMuravjov commented on OCamlTyEff/lib/tychk.ml
> +;;
Нет, обычные и "эффектные" типовые переменные не могут пересекаться, если не считать пересечением подстановку вместо обычной типовой переменной типа функции с переменными эффектами (или составного типа, содержащего такой тип функции).

Функция `mrg_subst` производит объедениение двух подстановок:
- Сначала к подстановке `subst1` добавляются все подстановки обычных типовых переменных из `subst2`
- Потом добавляются подстановки "эффектных" типовых переменных из `subst2` к полученной на предыдущем шаге подстановке `subst`, которая содержит подстановки обычных типовых переменных из `subst1` и `subst2` и подстановки "эффектных" типовых переменных только из `subst1`

Пример на псевдокоде для `subst1 = (['a = int], ['e = IO])`, `subst2 = (['b = bool], ['f = exc Exc1])`:
- `subst = (['a = int; 'b = bool], ['e = IO])`
- Результат `mrg_subst`: `(['a = int; 'b = bool], ['e = IO; 'f = exc Exc1])`

2021-12-26 17:50 UTC, IlyaMuravjov commented on OCamlTyEff/lib/ast.ml
> +;;
Укоротил

2021-12-27 16:37 UTC, Kakadu commented on OCamlTyEff/lib/interpret.ml
> +  val fold : ('a, 'e) t -> ok:('a -> 'b) -> err:('e -> 'b) -> 'b
Скорее всего это называется не fold, а map сразу по двум аргументам, т.е. bimap

2021-12-27 16:37 UTC, Kakadu commented on OCamlTyEff/lib/interpret.ml
> +      "This kind of expression is not allowed as right-hand side of `let rec %s`"
Вроде это не ошибка интепретации

2021-12-27 17:39 UTC, IlyaMuravjov commented on OCamlTyEff/lib/tychk.ml
> +;;
Переименовал

2021-12-27 17:40 UTC, IlyaMuravjov commented on OCamlTyEff/lib/tychk.ml
> +let rec unbind_ty_eff_vars env ty =
Переименовал

2021-12-27 17:40 UTC, IlyaMuravjov commented on OCamlTyEff/lib/ast.ml
> +let _or = Or
Переименовал

2021-12-27 17:40 UTC, IlyaMuravjov commented on OCamlTyEff/lib/ast.ml
> +  | CString s -> fprintf fmt "\"%s\"" s
Исправил

2021-12-27 17:40 UTC, IlyaMuravjov commented on OCamlTyEff/lib/ast.ml
> +      (fun fmt eff -> pp_ptrn fmt eff)
Исправил

2021-12-27 17:41 UTC, IlyaMuravjov commented on OCamlTyEff/lib/tychk.ml
> +         | _ -> List.to_seq [ eff ])
Заменил на `Seq.return`

2021-12-27 17:41 UTC, IlyaMuravjov commented on OCamlTyEff/lib/tychk.ml
> +;;
Переименовал

2021-12-27 17:41 UTC, IlyaMuravjov commented on OCamlTyEff/lib/tychk.ml
> +;;
Заменил на `Seq.filter_map`

2021-12-27 17:42 UTC, IlyaMuravjov commented on OCamlTyEff/lib/tychk.ml
> +      TTuple tys, List.fold_left (fun e1 e2 -> EffSet.union e1 e2) EffSet.empty effss
Применил здесь и ещё в трёх местах

2021-12-27 17:42 UTC, IlyaMuravjov commented on OCamlTyEff/lib/tychk.ml
> +exception Empty_macth
Исправил

2021-12-27 17:42 UTC, IlyaMuravjov commented on OCamlTyEff/lib/tychk.ml
> +      | (ptrn1, case1) :: cases ->
Согласен, исправил

2021-12-27 18:09 UTC, IlyaMuravjov commented on OCamlTyEff/lib/interpret.ml
> +  val fold : ('a, 'e) t -> ok:('a -> 'b) -> err:('e -> 'b) -> 'b
Переименовал, изначально назвал по аналогии с `val fold : none:'a -> some:('b -> 'a) -> 'b option -> 'a`

2021-12-27 18:11 UTC, IlyaMuravjov commented on OCamlTyEff/lib/interpret.ml
> +      "This kind of expression is not allowed as right-hand side of `let rec %s`"
Согласен, могу заменить все `Invalid_rec s` на `Unbound s`, но, по-моему, лучше оставить более специализированное сообщение об ошибке.

Тайпчекер эту ошибку не обнаруживает, так как `let rec x : int = x` корректно с точки зрения типов.

2021-12-27 19:43 UTC, Kakadu commented on OCamlTyEff/lib/interpret.ml
> +      "This kind of expression is not allowed as right-hand side of `let rec %s`"
В настоящем OCaml -- некорректно

2021-12-27 19:45 UTC, Kakadu commented on OCamlTyEff/lib/tychk.ml
> +    (ELet
Я подразумевал, что ручные тесты парсера отдельно, а тайпчекер можно тестить уже более компактно.

2021-12-27 19:47 UTC, Kakadu commented on OCamlTyEff/lib/ast.ml
> +[@@deriving eq, show { with_path = false }]
А в каком смысле это нативные штуки?

2021-12-27 19:48 UTC, Kakadu commented on OCamlTyEff/lib/ast.ml
> +[@@deriving eq, show { with_path = false }]
А, понял

2021-12-27 19:49 UTC, Kakadu commented on OCamlTyEff/lib/parser.ml
> +  | "class"
Это лучше в коммент запихнуть. Для будущих поколений

2021-12-27 19:59 UTC, Kakadu commented on OCamlTyEff/lib/tychk.ml
> +;;
Думаю, что last_id стоит сделать недоступным вне этой функции, чтобы ни у кого не возникло ложных желаний...

2021-12-27 20:00 UTC, Kakadu commented on OCamlTyEff/lib/std.ml
> +    }
Сделайте какую-нить доку, чтобы было понятно, что имеется в виду под sneaky_eff

2021-12-27 20:13 UTC, Kakadu commented on OCamlTyEff/lib/tychk.ml
> +;;
Получается что обычные типы могут содержать эффектные типовые переменные, но не наоборот. Тогда видится более правильным в начале подставить все эффектные типовые переменные, а уже потом подставлять обычные типовые, иначе можно что-то недоподставить. Наверное можно сконструировать пример типа `subst1 = ([], [ 'e=IO ])`, `subst2 = ([ 'a -['e]-> 'b ],[]))`. Если подставить обычные перед эффектными, то получится `([ 'a -['e]-> 'b ], [ 'e=IO ])` а хотелось бы  `([ 'a -[IO]-> 'b ], [ 'e=IO ])`

Но вообще я имел в виду, что было бы с точки зрения читаемости построить сначала один элемент записи, а потому второй, и вернуть их как значения типа `subst`. А то начинает казаться, что при свертке изменяются оба элемента параллельно, а на деле, по-видимому, по отдельности.

2021-12-28 15:06 UTC, IlyaMuravjov commented on OCamlTyEff/lib/tychk.ml
> +;;
Мы сейчас обсуждаем функцию `mrg_subst`. Она ничего никуда не подставляет, а занимается объединением двух подстановок (двух наборов правил вида: "подставьте `ty` вместо `'a`"). Применение этих правил к конкретному типу - это уже дело функции `apply_subst`, которая у меня реализован так, что она, когда натыкается на типовую переменную `'a` и видит правило "подставьте `ty` вместо `'a`", не просто заменяет `'a` на `ty`, а заменяет `'a` на `apply_subst ty subst env`, т.е. внутри правил подстановки не обязательно всё должно быть до конца подставлено, поэтому набор правил "подставьте `'a -[IO]-> 'b` вместо `'x`" и "подставьте `IO` вместо `'e`" эквивалентен набору правил "подставьте `'a -['e]-> 'b` вместо `'x`" и "подставьте `IO` вместо `'e`" (во втором случае вместо `'x` сначала будет подставляться `'a -['e]-> 'b`, а потом уже внутри `'a -['e]-> 'b` вместо `'e` будет подставляться `IO`).

Теперь про разделение построения правил подстановки для обычных и "эффектных" типовых переменных. Я сомневаюсь, что его можно сделать, потому что, как Вам правильно "начинает казаться", "при свертке изменяются оба элемента параллельно", например, при объединении следующих правил подстановки обычных типовых переменных: "подставьте `'a -[IO]-> 'b` вместо `'x`" и "подставьте `'a -['e]-> 'b` вместо `'x`" - появляется правило подстановки "эффектной" типовой переменной "подставьте `IO` вместо `'e`".

Для упрощения понимания тайпчекера я добавил тесты, соответствующие упомянутым примерам, и немного упростил реализацию связанной функции `unify`, переиспользовав код из `equal_ty`.

2021-12-28 15:10 UTC, IlyaMuravjov commented on OCamlTyEff/lib/interpret.ml
> +      "This kind of expression is not allowed as right-hand side of `let rec %s`"
Я и не говорю, что `let rec x : int = x` корректно, я лишь говорю, что оно "корректно с точки зрения типов" (в `int` записывается `int`), поэтому такие ошибки не обнаруживаются тайпчекером, но их теоретически до интерпретации может обнаруживать другой анализатор AST, которого у меня нет.

2021-12-28 15:28 UTC, IlyaMuravjov commented on OCamlTyEff/lib/parser.ml
> +  | "class"
Запихнул

2021-12-28 15:29 UTC, IlyaMuravjov commented on OCamlTyEff/lib/std.ml
> +    }
Сделал

2021-12-28 15:42 UTC, IlyaMuravjov commented on OCamlTyEff/lib/tychk.ml
> +;;
Сделал и ещё добавил тест интерпретатора для аналогичного сценария: присвоение по локальной ссылке из анонимной функции, вызываемой извне области видимости этой локальной ссылки.

2021-12-28 16:54 UTC, Kakadu commented on OCamlTyEff/lib/interpret.ml
> +      "This kind of expression is not allowed as right-hand side of `let rec %s`"
В OCaml это  ошибка типизации

2021-12-28 17:24 UTC, Kakadu commented on OCamlTyEff/lib/tychk.ml
> +;;
Складывается впечателение, что Вы понимаете, что происходит

2021-12-28 17:25 UTC, Kakadu approved these changes

2021-12-28 17:25 UTC, merged

2021-12-28 18:25 UTC, IlyaMuravjov commented on OCamlTyEff/lib/interpret.ml
> +      "This kind of expression is not allowed as right-hand side of `let rec %s`"
Хорошо, [реализовал](https://github.com/IlyaMuravjov/fp2021/commit/e6c7233dd4bad3bcbe30d90621d87b52256bf33b) статический поиск таких ошибок