Kotlin
Kakadu/fp2021 pull request #19
Opened 2021-12-29 23:14 UTC by IAmFunkyFrog

Попытка написать интерпретатор чего-то похожего на Котлин

2021-12-31 08:45 UTC, Kakadu commented
А у вас воспроизведется проблема, описанная тут?
https://counterexamples.org/under-construction.html

2021-12-31 09:10 UTC, Kakadu requested changes
Очень больно читать.

2021-12-31 09:10 UTC, Kakadu commented on Kotlin/lib/interpreter.ml
> +               && Base.phys_equal func_eval_ctx.last_return_value Unitialized
Ну-ка расскажите как  Base.phys_equal работает

2021-12-31 09:10 UTC, Kakadu commented on Kotlin/lib/interpreter.ml
> +    Base.Option.value_exn (Base.Result.ok (load_standard_classes ctx))
Наверняка можно было ещё сложнее написать

2021-12-31 09:10 UTC, Kakadu commented on Kotlin/lib/interpreter.ml
> +    ; last_derefered_variable : record_t option
И что это?

2021-12-31 11:39 UTC, IAmFunkyFrog commented on Kotlin/REPL.ml
> +      let line = Option.value_exn (In_channel.input_line In_channel.stdin) in
В случае, если напечатать ctrl + d, там будет None

2021-12-31 11:41 UTC, IAmFunkyFrog commented on Kotlin/lib/ast.ml
> +  | AnonymousFunctionDeclaration of statement
AnonymousFunctionDeclaration всегда содержит statement = AnonymousFunctionDeclarationStatement, и там аргумента сохранены (добавлю комментарий по этому поводу)

2021-12-31 11:45 UTC, IAmFunkyFrog commented on Kotlin/lib/tests.ml
> +  | Ok eval_ctx -> eval_ctx.last_eval_expression = BooleanValue false
Наверно можно было сделать ```| Ok eval_ctx when ... -> true```, но я не совсем понимаю, чем это лучше, а если можно сделать как-то еще, то я этого не знаю

2021-12-31 12:33 UTC, IAmFunkyFrog commented on Kotlin/lib/utils.ml
> +  | InitStatementNotInClass
Теперь парсер не должен создавать ошибки такого типа

2021-12-31 12:38 UTC, IAmFunkyFrog commented on Kotlin/lib/interpreter.ml
> +               && Base.phys_equal func_eval_ctx.last_return_value Unitialized
Изначально тут вместо phys_equal использовался оператор ==, но после ```make release``` выпало сообщение, что данный оператор устарел и что предпочтительно использовать phys_equal, и по этой причине он здесь

2021-12-31 14:15 UTC, IAmFunkyFrog commented
> А у вас воспроизведется проблема, описанная тут? https://counterexamples.org/under-construction.html

На данный момент поля, помеченные ```val``` модификатором, необходимо инициализировать прямо на месте их объявления.
Например:
> class MyClass(initValue: Int) {
   public val innerValue: Int = initValue
}

Таким образом, если запустить такой код, то текущая (на момент 31 декабря) версия интерпретатора выдаст ошибку:
> Kotlin REPL
Type @help for getting further information
&gt;&gt; class Foo() {
&gt;&gt; &nbsp;&nbsp;val nonNull: String
&gt;&gt; &nbsp;&nbsp;fun crash() {
&gt;&gt; &nbsp;&nbsp;&nbsp;&nbsp;this.nonNull.startsWith("foo")
&gt;&gt; &nbsp;&nbsp;}
&gt;&gt; &nbsp;&nbsp;init {
&gt;&gt; &nbsp;&nbsp;&nbsp;&nbsp; this.crash()
&gt;&gt; &nbsp;&nbsp;&nbsp;&nbsp; this.nonNull = "foo_Initialized"
&gt;&gt; &nbsp;&nbsp;}
&gt;&gt; };;
Kotlin REPL # <REPL empty answer&gt;
&gt;&gt; val foo: Foo = Foo();;
Kotlin REPL # Utils.ExpectedObjectToDereference

Однако даже если попытаться переписать ```init``` блок на:
> init {
&nbsp;&nbsp;this.nonNull = "foo_Initialized"
&nbsp;&nbsp;this.crash()
    }

Код все равно не сработает так, как ожидается в настоящем Котлин, так как формально поле ```nonNull``` неизменяемое. Это недоработка, и ее надо исправить

2022-01-01 09:40 UTC, Kakadu commented on Kotlin/lib/interpreter.ml
> +               && Base.phys_equal func_eval_ctx.last_return_value Unitialized
Это не то, что я спросил

2022-01-01 09:40 UTC, Kakadu commented on Kotlin/REPL.ml
> +      let line = Option.value_exn (In_channel.input_line In_channel.stdin) in
Добавьте коммент, а то не очевидно

2022-01-01 09:44 UTC, Kakadu commented on Kotlin/lib/ast.ml
> +  | AnonymousFunctionDeclaration of statement
Это говнокод. Вам никто не рассказывал, что некорректные данные не должны типизироваться?

2022-01-02 21:12 UTC, IAmFunkyFrog commented on Kotlin/REPL.ml
> +open Core
Ничего, поменял на Base и Stdio

2022-01-02 21:29 UTC, IAmFunkyFrog commented on Kotlin/lib/interpreter.ml
> +               && Base.phys_equal func_eval_ctx.last_return_value Unitialized
Да, извините, я просто не нашелся что ответить, так как не сразу нашел источник, где описывалось бы, как работает phys_equal. 
[Кажется](https://dev.realworldocaml.org/maps-and-hashtables.html#and-phys_equal ), phys_equal сравнивает, что две структуры данных имеют один и тот же указатель в память. 
Также теперь кажется, что это не то, что мне надо

2022-01-02 22:30 UTC, IAmFunkyFrog commented on Kotlin/lib/interpreter.ml
> +    | AnonymousFunction of object_t ref option
Должны были и даже рассказывали

2022-01-03 13:57 UTC, Kakadu commented
Пока в процессе, я помечу как черновик

2022-01-03 20:48 UTC, IAmFunkyFrog commented on Kotlin/lib/ast.ml
> +  | AnonymousFunctionDeclaration of statement
Переделал

2022-01-03 20:50 UTC, IAmFunkyFrog commented on Kotlin/lib/interpreter.ml
> +    | AnonymousFunction of object_t ref option
Строго обязательны не все, ненужные убрал

2022-01-07 13:42 UTC, IAmFunkyFrog commented on Kotlin/lib/demos.ml
> +    })
Немного улучшил парсер, теперь последнюю лямбду - аргумент можно передавать как в настоящем Котлин:
`distances.map {index: Int, old: Int ->  infinity }`

2022-01-07 13:43 UTC, IAmFunkyFrog commented on Kotlin/lib/interpreter.ml
> +      | _ -> failwith "Should not reach here")
Постарался подтереть лишние `failwith "should not reach here"`

2022-01-11 19:46 UTC, Kakadu requested changes
Я думаю, что надо сначале прокомментировать каждое вхождение мутабельных и объяснить зачем она там действительно нужна.

2022-01-11 19:46 UTC, Kakadu commented on Kotlin/lib/ast.ml
> +  }
Что-то мне подсказывает, что вот это не кусок AST. 
А если  и кусок, который обозначает переменные, то не очень понятно как при множественном вхождении одной переменной, присваивание будет распространяться на все вхождения. Или как при рекурсии будет старое значение заменяться новым?

А вообще, могли уж и мутабельное поле сделать, а не ref'ы.

И вообще, обоснуйте как-нибудь, почему Вы забили на всё что я рассказывал про чистые функции

2022-01-11 19:46 UTC, Kakadu commented on Kotlin/lib/utils.ml
> +[@@deriving show]
Это в куче ошибки типизации и интерпретации? Может не стоит их так смешивать?

2022-01-11 19:46 UTC, Kakadu commented on Kotlin/lib/ast.ml
> +  ; statement : statement
Почему не statement list? У вас же наверняка ожидается, что там всегда "block".

2022-01-12 16:20 UTC, IAmFunkyFrog commented on Kotlin/lib/ast.ml
> +  }
Попробую ответить по порядку:
1) Да, это мало относится непосредственно к AST и является представлением переменных внутри интерпретатора. Возможно стоит это вынести из AST, но я пока не придумал, как.
2) Не совсем понял вопрос про множественные вхождения и рекурсию, можно пример? 
3) Переделаю, действительно использовать конкретно ref какой-то мотивации не было
4) Сначала я пытался сделать все с чистыми функциями как вы и рассказывали, но у меня по ходу дела возникли некоторые проблемы, и я сделал так, как оно сейчас есть. Кажется проблемы были связаны с тем, чтобы изменять внешние по отношению к телу функции переменные, то есть проблемным стал примерно такой код <pre>
fun main() {
    var x: Int = 1
    fun updateX() {
        x = x + 1
    }
    updateX()
}
</pre>

2022-01-12 16:22 UTC, IAmFunkyFrog commented on Kotlin/lib/ast.ml
> +  ; statement : statement
Какой-то конкретной мотивации использовать именно statement, а не statement list не было, там действительно всегда ожидается Block и ничего другого парсер туда не производит

2022-01-13 19:33 UTC, Kakadu commented on Kotlin/lib/ast.ml
> +  }
> 1. Да, это мало относится непосредственно к AST и является представлением переменных внутри интерпретатора. Возможно стоит это вынести из AST, но я пока не придумал, как.

Попробуйте что-нибудь придумать, а то сваливать всё в кучу -- это отстой даже в мире обывателей на джавке.

> 2\. Не совсем понял вопрос про множественные вхождения и рекурсию, можно пример?

Ну, возьмем факториал на условном камле: 
```ocaml
let rec fac n = if n<=1 then n else fac (n-1) + (fac (n-2))
```
Если у Вас одно представление этой функции в памяти (что логично, так как функция одна тут). то при первом вызове (например, `fac 5`), в переменной n хранится 5. При втором вызове там хранится 4, но при это всё ещё хранится 5, так как вызов от 5-2 ещё предстоит сделать. Не очень понимаю как это работае.

2022-01-13 20:43 UTC, IAmFunkyFrog commented on Kotlin/lib/ast.ml
> +      (** Вырожденный случай Block. Нужен только для функции parse_and_run, и по сути является Block без фигурных скобок вокруг *)
Честно говоря, можно и без, просто в какой-то момент мне показалось, что лучше будет выделить эту сущность как отдельный элемент ast. Переделаю

2022-01-13 21:02 UTC, IAmFunkyFrog commented on Kotlin/lib/ast.ml
> +  ; statement : statement
Поправлю парсер. 
Я знаю, что можно писать
```ocaml
 type t = Point of { x: int; y: int }
```
, но видимо не понял, как конкретно здесь мог бы это использовать.

2022-01-14 21:04 UTC, IAmFunkyFrog commented on Kotlin/lib/utils.ml
> +[@@deriving show]
Попытался разделить эти ошибки на разные типы ошибок, а также добавил комментарии

2022-01-15 12:27 UTC, IAmFunkyFrog commented
> Я думаю, что надо сначале прокомментировать каждое вхождение мутабельных и объяснить зачем она там действительно нужна.

На данный момент во всем интерпретаторе осталось одно мутабельное поле внутри 
```ocaml
and variable_t =
  { var_typename : typename
  ; mutable_status : bool
  ; mutable value : value
  }
```
Попытаюсь объяснить, зачем оно нужно:
В моем интерпретаторе все переменные, функции и классы, не являющиеся полями или методами, хранятся в форме двух односвязных списков (один для локальных переменных и методов, второй для внешних по отношению к текущему блоку ``` { ... } ```). 
В один момент возникла проблема с тем, чтобы изменять внешние по отношению к текущему блоку переменные, и было решено сделать внутри переменных поле ``` value ``` изменяемым. 
Сейчас мне кажется, что можно было обойтись и без ``` mutable ```, и просто после интерпретации функции возвращать из нее каким-либо образом переменные, которая она изменила, однако успею ли я это поправить, чтобы оно работало без ``` mutable ``` я пока не знаю. Постараюсь успеть

2022-01-16 10:44 UTC, Kakadu commented on Kotlin/lib/interpreter.ml
> +    ; scope : scope_type
У меня есть ощущение, что наверняка поля в этой структуре как-то между собой связаны.

2022-01-16 10:45 UTC, Kakadu commented on Kotlin/lib/interpreter.ml
> +    ; scope : scope_type
В смысле, "что-то не может быть чем-то, когда что-то другое чему-то равно"

2022-01-17 14:53 UTC, IAmFunkyFrog commented on Kotlin/lib/interpreter.ml
> +    ; scope : scope_type
Честно говоря, там действительно есть неявные связи между некоторыми полями, я сейчас занимаюсь тем, чтобы это исправить

2022-01-17 17:32 UTC, IAmFunkyFrog commented on Kotlin/lib/interpreter.ml
> +    ; scope : scope_type
Убрал лишние поля, объединив их в один тип

2022-01-17 17:46 UTC, IAmFunkyFrog commented on Kotlin/lib/ast.ml
> +  }
> 1. Да, это мало относится непосредственно к AST и является представлением переменных внутри интерпретатора. Возможно стоит это вынести из AST, но я пока не придумал, как.
Возвращаясь к этому вопросу, вынес из ast.ml то, что не относится непосредственно к AST

2022-01-18 15:16 UTC, IAmFunkyFrog commented
Извините пожалуйста, времени до экзамена осталось совсем мало, если есть что-то конкретное, что нужно сделать, чтобы получить зачет, можно это узнать?

2022-01-18 16:37 UTC, Kakadu commented
> Извините пожалуйста, времени до экзамена осталось совсем мало, если есть что-то конкретное, что нужно сделать, чтобы получить допуск, можно это узнать?

Вы на какую макс. оценку хотите допуск. Я вот сейчас с подозрением смотрю на костыль для типа Dynamic...

2022-01-18 16:59 UTC, Kakadu commented
А вообще, лучше пихать код на Котлине вне Окамла, как здесь сделано: https://github.com/Kakadu/fp2021/blob/master/Lambda/demos/parsingTests.t
А то может я делаю что-то не так, и поэтому получаю ` Test failed: (Interpreter (UnknownFunction "main"))`. И для императивного факториала тоже
```kotlin

      fun fact(m: Int): Int {
        var acc = 1
        var n = m;
        while (n>1) {
            acc = acc * n;
            n = n-1
        }
        return acc
      }

      fun main() {
        println(fact(5))
      }
```

2022-01-18 18:01 UTC, IAmFunkyFrog commented
> А вообще, лучше пихать код на Котлине вне Окамла, как здесь сделано: https://github.com/Kakadu/fp2021/blob/master/Lambda/demos/parsingTests.t А то может я делаю что-то не так, и поэтому получаю ` Test failed: (Interpreter (UnknownFunction "main"))`. И для императивного факториала тоже
> 
> ```kotlin
>       fun fact(m: Int): Int {
>         var acc = 1
>         var n = m;
>         while (n>1) {
>             acc = acc * n;
>             n = n-1
>         }
>         return acc
>       }
> 
>       fun main() {
>         println(fact(5))
>       }
> ```

Нет, вы все делаете так, это скорее мой интерпретатор не достаточно хорош. Если взять этот код и
1. Аннотировать переменные типами
2. Убрать ``` ; ``` (они не поддержаны в текущей версии парсера)

То пример заработает (я добавил его в примеры). 

Факториал в cps не работает по той же причине - не поддержаны аргументы лямбд без явного указания типов (в частности, нужно преобразовать ``` { l -> k(l * n) } ``` к ``` { l: Int -> k(l * n) } ```, и оно заработает)

2022-01-18 18:03 UTC, IAmFunkyFrog commented
> > Извините пожалуйста, времени до экзамена осталось совсем мало, если есть что-то конкретное, что нужно сделать, чтобы получить допуск, можно это узнать?
> 
> Вы на какую макс. оценку хотите допуск? Я вот сейчас с подозрением смотрю на костыль для типа Dynamic...

Ну хотелось бы конечно на С, чтобы побороться за стипендию, но если не наработал, то готов и меньшую оценку, тогда чтобы просто зачет был хотя бы

2022-01-18 18:13 UTC, Kakadu commented
> 2\. Убрать `;` (они не поддержаны в текущей версии парсера)

Но почему лишние ; приводят к ошибке `(Interpreter (UnknownFunction "main"))`? Это же бред?

2022-01-18 18:16 UTC, Kakadu commented
А Fixpoint там получится написать? А то я не умею в Котлин

2022-01-18 19:07 UTC, IAmFunkyFrog commented
> > 2. Убрать `;` (они не поддержаны в текущей версии парсера)
> 
> Но почему лишние ; приводят к ошибке `(Interpreter (UnknownFunction "main"))`? Это же бред?

И правда бред, был баг в парсере с тем, что не проверялось, достигнуть ли конец входных данных (строки с программой) после парсинга

2022-01-18 19:17 UTC, IAmFunkyFrog commented
> А Fixpoint там получится написать? А то я не умею в Котлин

Попытался в демо с факториалами докинуть еще fixpoint-овый факториал

2022-01-18 22:02 UTC, IAmFunkyFrog commented
Вы там добавили странный тест "LOOP" с вопросом почему он печатает 120. Проблема была в том, что в функцию parse_and_run передавалась не та программа (что конкретно было не так можно посмотреть в дифе последнего комита, там 2 строчки)

2022-01-19 09:41 UTC, IAmFunkyFrog commented
С тестом "plus via many +1" была проблема в том, что у меня не поддержан такой синтаксис для вызова функций. Мой парсер ожидает, что если вызывается функция\метод, то это будет выглядеть как ``` function_name(arg1, arg2, ...) ```, но если написать ``` function_name(arg1, arg2, ...)() ``` то это не распарсится

2022-01-19 11:46 UTC, Kakadu approved these changes

2022-01-19 11:52 UTC, merged