Asm interpreter
Kakadu/fp2021 pull request #20
Opened 2022-01-03 08:40 UTC by shlegelal

2022-01-03 15:36 UTC, Kakadu requested changes
Меня всё-таки беспокоит, что обилие строчек в коде -- это не типизированный стиль, а питон какой-то

2022-01-03 15:36 UTC, Kakadu commented on asm/lib/interpret.ml
> +        | Instruction _ -> error "invalid combination of opcode and operands"
При наличии хоть какого-то AST не пришлось бы делать runtime проверки на арность и компилятор бы подсказал, что случаи разобраны или нет.

2022-01-03 15:36 UTC, Kakadu commented on asm/lib/interpret.ml
> +          match MapString.find "0jump" env0 with
Это магическая константа какая-то? В чем её суть?

2022-01-03 15:36 UTC, Kakadu commented on asm/lib/interpret.ml
> +              | _ -> error "fatal error" )
В таких местах надо подробнее писать, что за ошибка, чтобы такие как я могли понят почему это fatal.
Вообще, для разных видов ошибок лучше отдельный тип завести, а не возвращать строчки.

2022-01-03 15:36 UTC, Kakadu commented on asm/lib/interpret.ml
> +              ([l] @ st)
:)

2022-01-03 15:36 UTC, Kakadu commented on asm/lib/interpret.ml
> +          | 60L ->
Снова магические константы

2022-01-03 15:36 UTC, Kakadu commented on asm/lib/interpret.ml
> +                (String.concat "" ["R"; String.sub s 1 1; "X"])
Очень сложно!

2022-01-03 15:36 UTC, Kakadu commented on asm/lib/interpret.ml
> +        | Instruction _ -> error "invalid combination of opcode and operands"
И ниже тоже

2022-01-03 15:44 UTC, shlegelal commented on asm/lib/interpret.ml
> +      | k when k = -1L -> acc ^ "\x80"
0b1000_0000 или ведущая 1

2022-01-03 15:47 UTC, shlegelal commented on asm/lib/interpret.ml
> +    let env_set id v env9 =
Идентификаторы нужны были мне, чтобы не запутаться в многочисленных переопределениях, постараюсь убрать ненужные

2022-01-03 15:53 UTC, shlegelal commented on asm/lib/interpret.ml
> +          | 60L ->
да, это из документации ассемблера, а именно определенный системный вызов (exit).
Мне как-то нужно вынести константы и задокументировать?

2022-01-03 15:54 UTC, shlegelal commented on asm/lib/interpret.ml
> +              ([l] @ st)
(:

2022-01-03 17:42 UTC, shlegelal commented on asm/lib/ast.ml
> +and sec_dir = Section of string * in_sec_dir list
тут запутывает не взаимная рекурсия, а хороший нейминг :)

2022-01-03 18:20 UTC, shlegelal commented on asm/lib/ast.ml
> +and sec_dir = Section of string * in_sec_dir list
рука-лицо. поняла о чем речь

2022-01-03 19:08 UTC, shlegelal commented on asm/lib/interpret.ml
> +          match MapString.find "0jump" env0 with
в ней сохраняется метка для прыжка, которая обрабатывается в другом месте

2022-01-03 20:16 UTC, shlegelal commented on asm/lib/ast.ml
> +and sec_dir = Section of string * in_sec_dir list
исправлено

2022-01-03 20:16 UTC, shlegelal commented on asm/lib/interpret.ml
> +      | k when k = -1L -> acc ^ "\x80"
добавлен коммент

2022-01-03 20:16 UTC, shlegelal commented on asm/lib/interpret.ml
> +      | Some _ -> return (MapString.add id v env9) in
опечатка -> убран match

2022-01-03 20:16 UTC, shlegelal commented on asm/lib/interpret.ml
> +    let env_set id v env9 =
убраны

2022-01-03 20:16 UTC, shlegelal commented on asm/lib/interpret.ml
> +              ([l] @ st)
исправлено

2022-01-03 20:19 UTC, shlegelal commented on asm/lib/interpret.ml
> +          | 60L ->
добавлен коммент

2022-01-03 20:19 UTC, shlegelal commented on asm/lib/interpret.ml
> +                (String.concat "" ["R"; String.sub s 1 1; "X"])
сделано легче

2022-01-04 14:49 UTC, Kakadu requested changes

2022-01-04 14:49 UTC, Kakadu commented on asm/lib/interpret.ml
> +    helper "" i
А не лучше ли будет воспользоваться Format.printf?

2022-01-04 19:33 UTC, Kakadu requested changes

2022-01-04 19:33 UTC, Kakadu commented on asm/lib/interpret.ml
> +              helper env foo 1 1 (String.of_seq (List.to_seq ['R'; s.[1]; 'X']))
Всё ещё очень сложно

2022-01-04 19:33 UTC, Kakadu commented on asm/demos/parsingTests.t
> +  >
Я хз что это за программа, что она должна делать и какой результат правильный. Сделайте какие-нибудь программы с понятным поведением, начав с факториала

2022-01-04 19:33 UTC, Kakadu commented on asm/lib/interpret.ml
> +        | Instruction _ -> error "invalid combination of opcode and operands"
Скажу явно, этот говнокод надо исправлять, потому что Вы игнорируете самое полезное, что есть в ФП

2022-01-04 19:33 UTC, Kakadu commented on asm/demos/parsingTests.t
> +
И ещё я хочу иметь возможность убедиться, что данный ассемблер является настоящим, т.е. понятно как его скомпилировать и запустить в GNU/Linux (я это в условии писал)

2022-01-04 19:33 UTC, Kakadu commented
И с копипастой из-за клонов тоже надо что-то сделать.

2022-01-11 15:44 UTC, Kakadu commented on asm/demos/asm_try/demo3.asm
> +
Почему-то demo3 ничего не печатает, когда я его запускаю.
По хорошему, надо всё компилять не Makefile а дюной, и запихнуть в тесты https://dune.readthedocs.io/en/stable/dune-files.html#rule

И не забыть добавить nasm в depexts.

2022-01-11 16:10 UTC, Kakadu commented on asm/lib/parser.ml
> +      return (Mnemonic (String.uppercase_ascii s))
Давайте я придерусь к двойному вызову одного и того же :)

2022-01-11 16:14 UTC, Kakadu commented on asm/lib/ast.ml
> +[@@deriving show {with_path = false}]
Я не вполне понимаю, что такое Dup

2022-01-11 16:14 UTC, Kakadu commented on asm/lib/interpret.ml
> +    helper "" i
Может быть можно всю функцию заменить на вызов Format.sprintf?

2022-01-11 16:17 UTC, Kakadu commented on asm/lib/interpret.ml
> +    | Er
Я не очень понял как задумано использовать Er, и почему из-за него выскакивает иногда ошибка  "byte data exceeds bounds"

2022-01-11 16:20 UTC, Kakadu commented on asm/lib/interpret.ml
> +              | _ -> error "fatal error" )
ы?

2022-01-11 16:21 UTC, Kakadu commented on asm/lib/interpret.ml
> +      Format.pp_print_flush Format.std_formatter ();
короче будет писать через формат "%!"

2022-01-11 16:38 UTC, shlegelal commented on asm/lib/ast.ml
> +[@@deriving show {with_path = false}]
6 DUP 's' -> 'ssssss'

2022-01-11 16:38 UTC, shlegelal commented on asm/lib/interpret.ml
> +    | Er
если в секции дата есть инструкции, то ничего страшного, но если к этим инструкциям обратиться, то выпадет эта ошибка.

2022-01-11 16:38 UTC, shlegelal commented on asm/demos/interpretingTests.t
> +   "0jump": (Ls ""),
метки могут начинаться только с букв или 4 специальных символов

2022-01-11 16:44 UTC, shlegelal commented on asm/lib/ast.ml
> +[@@deriving show {with_path = false}]
6 dup 's' -> 'ssssss'

2022-01-13 07:41 UTC, shlegelal commented on asm/demos/interpretingTests.t
> +  > section .text
2^8

2022-01-13 07:45 UTC, shlegelal commented on asm/demos/interpretingTests.t
> +  >     mov     rdi,rAx
да

2022-01-13 07:51 UTC, shlegelal commented on asm/lib/parser.ml
> +      return (Mnemonic (String.uppercase_ascii s))
А куда здесь вставить присваивание?

2022-01-13 07:58 UTC, shlegelal commented on asm/lib/interpret.ml
> +      Format.pp_print_flush Format.std_formatter ();
мне не понравилось: форматирование съехало

2022-01-13 11:25 UTC, Kakadu commented on asm/demos/interpretingTests.t
> +  >     mov     rdi,rAx
Какая?

2022-01-13 11:26 UTC, Kakadu commented on asm/lib/interpret.ml
> +      Format.pp_print_flush Format.std_formatter ();
Придется скрепя сердце исправлять

2022-01-13 11:26 UTC, Kakadu commented on asm/lib/ast.ml
> +[@@deriving show {with_path = false}]
А зачем так сделано?

2022-01-13 11:28 UTC, Kakadu commented on asm/demos/interpretingTests.t
> +   "0jump": (Ls ""),
У вас снова stringly-typed штука получается. Ай-я-яй. 
Может можно 0jump не складывать в ту же мапу?

2022-01-13 11:29 UTC, Kakadu commented on asm/demos/interpretingTests.t
> +  > section .text
А, это пример не про SIMD. ОК тогда.

2022-01-13 11:32 UTC, Kakadu commented on asm/lib/interpret.ml
> +    helper "" i
А, я понял. То, что ниже -- не то, что нужно?
```
Printf.printf "%.25Lx" 11111L;;
0000000000000000000002b67- : unit = ()

```

2022-01-13 15:53 UTC, shlegelal commented on asm/lib/interpret.ml
> +    helper "" i
увы, это другое

2022-01-13 15:54 UTC, shlegelal commented on asm/demos/interpretingTests.t
> +  >     mov     rdi,rAx
проще писать код

2022-01-13 15:55 UTC, shlegelal commented on asm/demos/interpretingTests.t
> +   "0jump": (Ls ""),
а где ее хранить? в глобалках?

2022-01-13 16:04 UTC, shlegelal commented on asm/lib/ast.ml
> +[@@deriving show {with_path = false}]
в ассемблере? удобно видимо

2022-01-13 16:05 UTC, shlegelal commented on asm/lib/interpret.ml
> +      Format.pp_print_flush Format.std_formatter ();
а что исправлять?

2022-01-13 16:06 UTC, shlegelal commented on asm/lib/interpret.ml
> +      Format.pp_print_flush Format.std_formatter ();
как я понимаю вариант "короче" получается длиннее

2022-01-13 20:43 UTC, Kakadu commented on asm/lib/interpret.ml
> +      Format.pp_print_flush Format.std_formatter ();
А вы не в строчках измеряйте, а в идентификаторах (или размер камлёвого AST сравнивайте)

2022-01-13 20:44 UTC, Kakadu commented on asm/lib/ast.ml
> +[@@deriving show {with_path = false}]
Нет, в интерпретаторе. Я так понимаю, что этот тип для значений, что хранятся в регистрах?

2022-01-13 20:45 UTC, Kakadu commented on asm/demos/interpretingTests.t
> +   "0jump": (Ls ""),
Передавать в функцию интерпретации как аргумент, например.

2022-01-14 08:11 UTC, shlegelal commented on asm/demos/interpretingTests.t
> +  >     mov     rdi,rAx
ассемблер позволяет писать хоть лесенкой, можно писать и вообще без отступов. Я с помощью отступов отделяю циклы от последовательного кода

2022-01-14 08:18 UTC, shlegelal commented on asm/demos/interpretingTests.t
> +   "0jump": (Ls ""),
и носить его через все другие функции как окружение? Я, конечно, глупый, но какой профит в таскании по всем функциям 3 доп аргумента?

2022-01-14 08:21 UTC, shlegelal commented on asm/lib/ast.ml
> +[@@deriving show {with_path = false}]
да, еще их можно записать как метку и положить в регистр.

2022-01-14 08:23 UTC, shlegelal commented on asm/lib/interpret.ml
> +      Format.pp_print_flush Format.std_formatter ();
не понимаю

2022-01-15 18:04 UTC, shlegelal commented
Что нужно сделать, чтобы дотянуть до оценки C?

2022-01-16 12:32 UTC, Kakadu commented on asm/demos/interpretingTests.t
> +   "0jump": (Ls ""),
https://gitlab.com/Kakadu/fp2020course-materials/-/blob/master/code/miniml/inferencer.ml#L304
я же не таскаю явно последнюю введенную типовыю переменную тут.

2022-01-16 18:24 UTC, Kakadu commented on asm/lib/interpret.ml
> +          >>= fun i -> return (MapString.add "0cond" (R64 i) env)
А зачем Вы стали придумывать костыль, если по канону тут должен использоваться регистр EFLAGS ?
https://www.felixcloutier.com/x86/cmp

2022-01-16 18:55 UTC, Kakadu commented
Там в условии было что-то про матицы. У вас такое тоже есть, да?

2022-01-16 19:25 UTC, shlegelal commented on asm/lib/interpret.ml
> +          >>= fun i -> return (MapString.add "0cond" (R64 i) env)
по канону большинство этих флагов используются для float. К тому же мне нужен только один из них.

2022-01-17 14:14 UTC, shlegelal commented
Теперь матрицы есть

2022-01-17 14:14 UTC, shlegelal commented
> Там в условии было что-то про матицы. У вас такое тоже есть, да?

да

2022-01-17 16:38 UTC, merged