Ocaml adt
Kakadu/fp2021 pull request #21
Opened 2022-01-09 20:59 UTC by Mishavint

Ast
Parser
Interpreter
Demos

2022-01-09 22:59 UTC, Kakadu commented on OcamlADT/lib/parser.ml
> +    trim @@ helper disj conj_op @@ d.key d in
Это вручную выписанный fold_right?

2022-01-09 22:59 UTC, Kakadu commented on OcamlADT/lib/ast.ml
> +  | Or                          (*  ||  *)
Меня удивляет,что автоформаттер на такие отступы не проорался.

2022-01-09 23:05 UTC, Mishavint commented on OcamlADT/lib/ast.ml
> +  | Or                          (*  ||  *)
Я выключил автоформаттер для аст

2022-01-10 18:11 UTC, Kakadu commented on OcamlADT/lib/ast.ml
> +  | Or                          (*  ||  *)
Не надо так делать, я же говорил

2022-01-10 18:12 UTC, Mishavint commented on OcamlADT/lib/parser.ml
> +    trim @@ helper disj conj_op @@ d.key d in
Заменил на fold_right

2022-01-10 18:24 UTC, Mishavint commented on OcamlADT/lib/ast.ml
> +  | Or                          (*  ||  *)
Удалил игнор. Сейчас всё должно быть с автоформатированием

2022-01-11 21:57 UTC, Kakadu commented on OcamlADT/demos/demoOcamlAdt.t
> +  >  | string -> false
Мне интересно, что Вы хотели показать этим тестом, а что показали на самом деле?

2022-01-11 22:43 UTC, Mishavint commented on OcamlADT/demos/demoOcamlAdt.t
> +  >  | string -> false
Что работает `function`

2022-01-11 22:51 UTC, Kakadu commented on OcamlADT/demos/demoOcamlAdt.t
> +  >  | string -> false
А должно?

2022-01-11 22:58 UTC, Mishavint commented on OcamlADT/demos/demoOcamlAdt.t
> +  >  | string -> false
По хорошему да

2022-01-14 15:49 UTC, Kakadu commented on OcamlADT/demos/demoOcamlAdt.t
> +  >  | string -> false
А в настоящем окамле должно?

2022-01-14 16:40 UTC, Mishavint commented on OcamlADT/demos/demoOcamlAdt.t
> +  >  | string -> false
Нет. Поправил

2022-01-16 20:44 UTC, Kakadu commented
Сделайте какие-нибудь более содержательные тесты на алгебраические типы. Красно-черные деревья, например

2022-01-17 11:58 UTC, Kakadu commented on OcamlADT/lib/ast.ml
> +and acase = id * pattern
Я не очень понимаю что это, и почему для этого отдельный тип, и почему там pattern, а не pattern list

2022-01-17 11:59 UTC, Kakadu commented on OcamlADT/lib/ast.ml
> +  | ECons of expr * expr  (** hd :: tl              *)
А зачем делать отдельно EList и ECons?

2022-01-17 12:10 UTC, Kakadu commented on OcamlADT/lib/ast.ml
> +  | TAdt of id
А типовые параметры где?

2022-01-17 12:11 UTC, Kakadu commented on OcamlADT/lib/interpret.ml
> +and env = value option ref BindsMap.t
ref ? Зачем? Вам никто не рассказывал, что ФП это про чистые функции? Или Вы тут как-то производительность пытаетесь оптимизировать?

2022-01-17 12:11 UTC, Kakadu commented on OcamlADT/lib/interpret.ml
> +  | Match_exhaust
Может non-exhaust?

2022-01-17 12:17 UTC, Kakadu commented on OcamlADT/lib/interpret.ml
> +let vadt s v = VAdt (s, v)
Скорее всего, если бы эти функции были доступны в парсере, то он мог бы подсократиться.

2022-01-17 12:20 UTC, Kakadu commented on OcamlADT/lib/interpret.ml
> +        helper pts
Стандартную фукнцию тут не применить?

2022-01-17 12:36 UTC, Kakadu requested changes
Меня смущает остутсвие типизации, и поэтому это не совсем камл с алгебраическими типами.

2022-01-17 12:51 UTC, Mishavint commented on OcamlADT/lib/ast.ml
> +and acase = id * pattern
Это у меня используеться для 
| Number number -> number

2022-01-17 12:51 UTC, Mishavint commented on OcamlADT/lib/interpret.ml
> +        helper pts
Применил

2022-01-17 12:51 UTC, Mishavint commented on OcamlADT/lib/interpret.ml
> +  | Match_exhaust
Заменил

2022-01-17 13:05 UTC, Mishavint commented on OcamlADT/lib/interpret.ml
> +and env = value option ref BindsMap.t
Оно мне позволяет например при 
`let rec fac = fun n -> if (n <= 0) then 1 else n * (f (n - 1))` добaвить в окружение `fac -> ref None`, вычислить `fun n -> if (n <= 0) then 1 else n * n * (fac (n - 1))` и записывать то, во что оно вычилилось по ранее добавленной ссылке

2022-01-17 13:06 UTC, Mishavint commented on OcamlADT/lib/interpret.ml
> +let vadt s v = VAdt (s, v)
В парсере я не использую `value`

2022-01-17 13:07 UTC, Mishavint commented on OcamlADT/lib/ast.ml
> +  | ECons of expr * expr  (** hd :: tl              *)
Убрал EList

2022-01-17 13:31 UTC, Kakadu commented
Договорились на Е

2022-01-17 13:33 UTC, merged