al dente Ruby
Kakadu/fp2021 pull request #32
Opened 2022-01-21 23:26 UTC by SofuriHafe

## Parser part
### done:
- ### constants;
- ### arithmetic: (+, -, *, /, %);
- ### logic: (and, &&, or, ||);
- ### comparisons;
- ### brackets support;
- ### lambda: ("lambda{ | x, y | x + y }" type only);
- ### functions;
- ### classes;
- ### calls (incl. class func. calls);
- ### lists;
- ### if, while w/o "do", "then" keywords;
- ### assign;
- ### return, break, next;
- ### w/o tests for now in order to clarify requirements.

2022-01-22 13:25 UTC, Kakadu commented on Ruby/lib/ast.ml
> +  | Lambda of expression list * statement list
Почему expression list?

2022-01-22 13:26 UTC, Kakadu commented on Ruby/lib/ast.ml
> +  | Assign of expression * expression
1+1 := 5?

2022-01-22 13:27 UTC, Kakadu commented on Ruby/lib/ast.ml
> +  | Return of expression
А просто return в Ruby нет?

2022-01-22 13:29 UTC, Kakadu requested changes
AST несколько подозрительное.

2022-01-23 20:49 UTC, SofuriHafe commented
> AST несколько подозрительное.

Что подразумевается под словом "подозрительное"?

> А просто return в Ruby нет?

Есть.
Добавил его поддержку в парсер.
Если будет вызван "простой return", то по факту вернется `nil`, как и происходит в Ruby.

> 1+1 := 5?

Это распарсится, несмотря на абсурд. Но легко исправляется.
Однако я пока решил оставить.

> Что такое Nil?
> 
> Добавьте документацию для конструкторов, где это не очевидно. Так чтобы она в HTML попадала.

Попытался добавить документацию для пунктов, которые могут показаться неочевидными.

> Почему expression list?

В этом _expression list_ будут сидеть аргументы, поэтому лист.
E.g. `lambda{ |x, y| x + y }`, где x и y, перечисленные через запятую, и будут ими.

2022-01-23 21:22 UTC, Kakadu commented
> > 1+1 := 5?
> 
> Это распарсится, несмотря на абсурд. Но легко исправляется. Однако я пока решил оставить.
Будем считать, что Вы это исправите потом


> > Почему expression list?
> 
> В этом _expression list_ будут сидеть аргументы, поэтому лист. E.g. `lambda{ |x, y| x + y }`, где x и y, перечисленные через запятую, и будут ими.

Тот же самый вопрос, что про  1+1

2022-01-23 21:35 UTC, SofuriHafe commented
> > > 1+1 := 5?
> 
> > 
> 
> > Это распарсится, несмотря на абсурд. Но легко исправляется. Однако я пока решил оставить.
> 
> 
> 
> Будем считать, что Вы это исправите потом
> 
> 
> 
> 
> 
> > > Почему expression list?
> 
> > 
> 
> > В этом _expression list_ будут сидеть аргументы, поэтому лист. E.g. `lambda{ |x, y| x + y }`, где x и y, перечисленные через запятую, и будут ими.
> 
> 
> 
> Тот же самый вопрос, что про  1+1

Если я правильно понимаю, то в этих случаях на месте _expression_ и его листа быть что-то типа _variable_.
Этот момент продумывался заранее, и ничего плохого в том, что variables будут обернуты в expression, я не увидел (_вроде_ переменные относятся всё-таки к expression, поэтому и вышло то, что вышло).

2022-01-23 21:38 UTC, Kakadu commented
> Этот момент продумывался заранее, и ничего плохого в том, что variables будут обернуты в expression, я не увидел

Будем надеяться, что Вы по ходу дела поймете, что там не так.

2022-01-23 21:39 UTC, merged