al dente Ruby
Kakadu/fp2021 pull request #34
Opened 2022-02-16 00:55 UTC by SofuriHafe

####  Additional parts:
- `interpreter`
- `demo`
- `tests`
#### List of key features:
- `anonymous funcs`, `closures`, `multiple assignments`, `recursive funcs`, `objects`, `method_missing`, `lists`, `calls`, `...`
#### (outdated) Features to be done/fixed are listed in README.md

2022-02-16 14:49 UTC, Kakadu commented on Ruby/lib/interpreter.ml
> +  (fun x -> x.value) rcd
Мне интересно, из каких соображений это написано именно так?

2022-02-17 15:34 UTC, SofuriHafe commented on Ruby/lib/interpreter.ml
> +  (fun x -> x.value) rcd
Не заметил при рефакторинге. Исправил.

2022-02-17 17:19 UTC, Kakadu commented
Я там попробовал запустить ваш пример на настоящем руби, и программа как-то быстро сломалась. Можете что-то с этим сделать?

2022-02-17 21:51 UTC, Kakadu requested changes
Попробуйте посмотреть на требуемые фичи языка и сделать по одному тестовому файлу на фичу. Чтобы меня легко убедить, что всё сделано.

2022-02-17 21:51 UTC, Kakadu commented on Ruby/lib/ast.ml
> +  | List of expression list
А почему тут expression list а не value list? Списки там ленивые и довычисляются когда по индексу обратишься? Если так, то надо про это написать

2022-02-17 21:51 UTC, Kakadu commented on Ruby/lib/ast.ml
> +  | CallLambda of identifier list * statement list * expression list
Это как-то очень сложно. Может отдельно объявление, отдельно вызов метода call?

2022-02-17 21:51 UTC, Kakadu commented on Ruby/lib/interpreter.ml
> +  sgnl : int;  (** SIGNAL: 0 -- nothing; 1 -- break; 2 -- next; 3 -- return *)
Алгебраические типы, не?

2022-02-20 19:19 UTC, SofuriHafe commented
Исправил некоторые замечания; добавил по тест-файлу на фичу

2022-02-21 18:45 UTC, SofuriHafe commented
ocamlformat с profile=default теперь не пропускает :(

2022-02-21 19:02 UTC, SofuriHafe commented on Ruby/lib/ast.ml
> +  | List of expression list
Добавил в документацию

2022-02-21 19:02 UTC, SofuriHafe commented on Ruby/lib/ast.ml
> +type identifier = Null | Identifier of string
Добавил в документацию

2022-02-21 19:02 UTC, SofuriHafe commented on Ruby/lib/ast.ml
>    | Call of identifier * identifier * expression list
Нет

2022-02-21 19:03 UTC, SofuriHafe commented on Ruby/lib/ast.ml
> +  | CallLambda of identifier list * statement list * expression list
Я вроде так и поступил: лямба и ее вызов и так отдельно

2022-02-21 19:03 UTC, SofuriHafe commented on Ruby/lib/interpreter.ml
> +let rec eval env single_statement =
Готово

2022-02-21 19:03 UTC, SofuriHafe commented on Ruby/lib/interpreter.ml
> +  let rec doer2 c = function [] -> c | hd :: tl -> doer2 (eval c hd) tl in
Исправил

2022-02-21 19:03 UTC, SofuriHafe commented on Ruby/lib/interpreter.ml
> +  | hd :: tl -> eval_stmts eval (eval ctx hd) tl
Исправил

2022-02-21 19:03 UTC, SofuriHafe commented on Ruby/lib/interpreter.ml
> +                match not (if_object (get_var_ctx_from_ctx i env).value) with
Исправил

2022-02-21 19:05 UTC, SofuriHafe commented
Интерпретатор стал монадическим, hooray!

2022-02-21 21:54 UTC, Kakadu requested changes

2022-02-21 21:54 UTC, Kakadu commented on Ruby/demos/anonymous.ml
> +let () = run_ruby [%blob "./rbs/anonymous.rb"]
https://github.com/Kakadu/fp2021/blob/master/Lambda/demos/parsingTests.t
Может стоит сделать как тут, чтобы не плодить лишние .ml файлы?

2022-02-21 21:54 UTC, Kakadu commented on Ruby/demos/rbs/recursion.rb
> +puts fib(10)
А комбинатор неподвиждной точки удастся?

2022-02-21 21:54 UTC, Kakadu commented on Ruby/lib/ast.ml
> +  | Identifier of string
Я так и не понял, зачем нужен Null

2022-02-21 21:54 UTC, Kakadu commented on Ruby/lib/ast.ml
> +  | Identifier of string
И коммент Вы не написали....

2022-02-21 21:54 UTC, Kakadu commented on Ruby/lib/ast.ml
> +  | Lambda of identifier list * statement list
Я так понимаю замыканий никоим образом нет?

2022-02-21 21:54 UTC, Kakadu commented on Ruby/lib/ast.ml
>    | Call of identifier * identifier * expression list
костыли

2022-02-21 21:54 UTC, Kakadu commented on Ruby/lib/ast.ml
> +  | CallLambda of identifier list * statement list * expression list
Нет, у Вас вызов просто и вызов лямбды. Самой лямбды нет.
Вы б комменты писали со схемой кода, что там ожидается

2022-02-21 21:54 UTC, Kakadu commented on Ruby/lib/interpreter.ml
> +    in
map?

2022-02-21 21:54 UTC, Kakadu commented on Ruby/lib/interpreter.ml
> +    { ctx with funcs = { id = i; args = a; stmts = s } :: ctx.funcs }
Прочитайте про record punning

2022-02-21 21:54 UTC, Kakadu commented on Ruby/lib/interpreter.ml
> +                   (combine_args_and_params (get_func_ctx_from_ctx i2 e_env).args x))
Вот тут Вы достаете функцию в предположении, что она есть, а выше проверяете. Не лучше ли доставать её сразу и возврщать None, когда её нет?

2022-02-21 21:54 UTC, Kakadu commented on Ruby/lib/interpreter.ml
> +                id = Identifier "tmp"
А не сломается ли чего-нибудь, если в исходной программе будет переменная 'tmp'? А почему?

2022-02-21 21:54 UTC, Kakadu commented on Ruby/lib/interpreter.ml
> +              (match (get_var_ctx_from_ctx i e_env).value with
Аналогично замечанию выше

2022-02-21 21:54 UTC, Kakadu commented on Ruby/lib/interpreter.ml
> +              @@ String (multliple_str_unpacker (get_var_ctx_from_ctx i e_env).value)
А если человек объявит свою функцию "to_s", то что там получится?

2022-02-21 21:54 UTC, Kakadu commented on Ruby/lib/ast.ml
> +  | Class
Я без понятия чем отличаются 2е от 4го. Нужна дока.

2022-02-21 21:54 UTC, Kakadu commented on Ruby/lib/interpreter.ml
> +        let rec through = function
А это не mmap, что был выше?

2022-02-21 21:54 UTC, Kakadu commented on Ruby/lib/interpreter.ml
> +              >>= fun x -> through1 (change_var_in_ctx hd x ctx) (List.tl elst) tl)
Мда, что-то как-то Вы не лучшем состоянии сознания писали эти функции...

2022-02-21 21:54 UTC, Kakadu commented on Ruby/lib/interpreter.ml
> +        | false -> fold_left (fun x -> stmt duo x) s_env s2)
Сократите

2022-02-21 21:54 UTC, Kakadu commented on Ruby/lib/interpreter.ml
> +            | hd :: tl -> stmt duo ctx1 hd >>= fun x -> doer x tl)
mmap?

2022-02-22 15:48 UTC, SofuriHafe commented on Ruby/demos/anonymous.ml
> +let () = run_ruby [%blob "./rbs/anonymous.rb"]
Кажется, что у меня получился еще менее копипастный способ.
Только я не придумал, как можно не дублировать ожидаемые результаты для Ruby и al dente Ruby; хотелось бы, чтобы указывать приходилось только один раз.

2022-02-22 15:58 UTC, SofuriHafe commented on Ruby/Makefile
> +	dune runtest
Не уловил к чему относится "не надо": либо к изменениям в Makefile, либо к списку задач для all.
Однако я вижу это как инструмент, и подгонять его под себя (это не командный проект) -- право работяг, если им так удобно.

Что касается автоформатирования, то тут это тоже не просто так. Если под настройкой VSCode подразумевалось форматирование во время сохранения, то это форматирование применяется только к одному файлу, который сохраняем. А хотелось бы сразу ко всем. И это пригодилось, когда выяснилось, что здесь теперь не пропускают profile=default по какой-то причине.

2022-02-22 16:00 UTC, SofuriHafe commented on Ruby/lib/ast.ml
> +  | Class
Добавил какое-то описание

2022-02-22 16:03 UTC, SofuriHafe commented on Ruby/lib/ast.ml
> +  | Identifier of string
Теперь вроде как добавил

2022-02-22 16:06 UTC, SofuriHafe commented on Ruby/lib/interpreter.ml
> +                   (combine_args_and_params (get_func_ctx_from_ctx i2 e_env).args x))
Готово

2022-02-22 16:06 UTC, SofuriHafe commented on Ruby/lib/interpreter.ml
> +        let rec through = function
Поменял содержание _through_ на _mmap_

2022-02-22 16:07 UTC, SofuriHafe commented on Ruby/lib/interpreter.ml
> +        | false -> fold_left (fun x -> stmt duo x) s_env s2)
Готово

2022-02-22 16:11 UTC, SofuriHafe commented on Ruby/lib/interpreter.ml
> +    in
Заменил

2022-02-23 08:35 UTC, Kakadu commented on Ruby/Makefile
> +	dune runtest
Форматирование надо было фиксить  ограничением  версиии на ocamlformat.

2022-02-23 08:36 UTC, Kakadu commented on Ruby/Makefile
> +	dune runtest
>  подгонять его под себя (это не командный проект) -- право работяг, если им так удобно.

Но я же тоже это компилирвать буду. Я паодогнал под себя с celan, а Вы всё испортили (с)

2022-02-23 08:38 UTC, Kakadu commented on Ruby/demos/rbs/recursion.rb
> +puts fib(10)
?

2022-02-23 08:39 UTC, Kakadu commented on Ruby/lib/ast.ml
> +  | Identifier of string
Ну а теперь сформулируйте почему это плохо и как это исправить.

2022-02-23 08:54 UTC, Kakadu commented on Ruby/lib/ast.ml
> +[@@deriving show { with_path = false }]
А эти префиксы -- это часть синтаксиса или соглашение об именах?

2022-02-23 08:55 UTC, Kakadu commented on Ruby/lib/ast.ml
> +  | Lambda of identifier list * statement list
А где у вас хранятся зацепленные значения?

2022-02-23 09:00 UTC, Kakadu commented on Ruby/lib/ast.ml
> +  | Lambda of identifier list * statement list
У вас есть на это пример, он работает, но я не понимаю как.

2022-02-23 09:02 UTC, Kakadu commented on Ruby/lib/ast.ml
> +  | CallLambda of identifier list * statement list * expression list
И поэтому, скорее всего, не получится сделать `(....).call(...).call(...)`. Интеерсно, как каррирование выглядит в руби?

2022-02-23 09:04 UTC, Kakadu commented on Ruby/lib/interpreter.ml
> +    doer (List.combine args params)
List.map2?

2022-02-23 09:06 UTC, Kakadu commented on Ruby/lib/interpreter.ml
> +    | h :: tl -> f h >>= fun c -> mmap f tl >>= fun lst -> return @@ (c :: lst)
А собаки зачем?

2022-02-23 09:16 UTC, Kakadu commented on Ruby/lib/interpreter.ml
> +  ;;
Напоминаеи mmap...

2022-02-23 09:17 UTC, Kakadu commented on Ruby/lib/interpreter.ml
> +      | true -> concat_var_lists (change_var_in_ctx hd.id hd.value base) tl)
Наверняка в модуле List есть подходящая функция.
И не лень вам это писапть.
Меня достало это читать.

2022-02-23 09:17 UTC, closed without merging