parser
Kakadu/fp2021 pull request #8
Opened 2021-09-30 22:10 UTC by AndrewOlejnikov

2021-10-01 14:48 UTC, Kakadu requested changes
Для начала неплохо. memcpy с арифметикой указателей внутри распарсится сейчас?

2021-10-01 14:48 UTC, Kakadu commented on C/lib/ast.ml
> +type c_expr =
А зачем везде в типах префикс `c_`? У Вас есть не сишные выражения в интерпретаторе?

2021-10-01 14:48 UTC, Kakadu commented on C/lib/ast.ml
> +  | INDEXER of string * c_expr
Допишите документацию тут, чтобы она в вебе отображалась. (Ссылка генерируется CI, но можно и локально смотреть). А то не понятно, что за строка здесь.

2021-10-01 14:48 UTC, Kakadu commented on C/lib/ast.ml
> +  | INITIALIZER of c_expr list
Аналогично

2021-10-01 14:48 UTC, Kakadu commented on C/lib/ast.ml
> +  | CARRAY of (int * c_values) list
Аналогично.

2021-10-01 14:48 UTC, Kakadu commented on C/dune-project
> +(maintainers "FIXME Vasya Pupkin")
:)

2021-10-01 14:49 UTC, Kakadu commented
Скорее всего линтер орёт на код, генеренный c помощью заклинания deriving. Можете забить пока

2021-10-03 09:46 UTC, AndrewOlejnikov commented
> Для начала неплохо. memcpy с арифметикой указателей внутри распарсится сейчас?

Теперь будет, раньше была ошибка с приоритетами для ( * ) и ( & )

2021-10-03 09:47 UTC, AndrewOlejnikov commented on C/lib/ast.ml
> +  | INDEXER of string * c_expr
Написал везде, где неочевидно из определения типа

2021-10-03 09:48 UTC, AndrewOlejnikov commented
> #### Результат поиска клонов
> 
> ```
> 
> Clone found (ocaml):
>  - C/lib/parser.ml [229:1 - 234:4] (5 lines, 94 tokens)
>    C/lib/parser.ml [138:7 - 142:3]
> 
> Clone found (ocaml):
>  - C/lib/parser.ml [229:1 - 234:4] (5 lines, 94 tokens)
>    C/lib/parser.ml [138:7 - 142:3]
> 
>  229 │ AndrewOlejnikov │ <= │ 138 │ AndrewOlejnikov │ let arrow =                                                              
>  230 │ AndrewOlejnikov │ == │ 139 │ AndrewOlejnikov │   indexer_exp <|> parens var_name <|> var_name >>= fun h ->              
>  231 │ AndrewOlejnikov │ == │ 140 │ AndrewOlejnikov │   many @@ (token "->" *> (indexer_exp <|> parens var_name <|> var_name)) 
>  232 │ AndrewOlejnikov │ == │ 141 │ AndrewOlejnikov │   >>= fun a -> return @@ List.fold_left arrow_cast h a                   
>  233 │ AndrewOlejnikov │ <= │ 142 │ AndrewOlejnikov │                                                                          
>  234 │ AndrewOlejnikov │    │ 143 │                 │ let                                                                      
> 
> Found 1 clones.
> Detection time:: 312.848ms
> Found 0 clones.
> Detection time:: 173.321ms
> Found 0 clones.
> Detection time:: 721.872ms
> ```

Пока что не понимаю как не копипастить функции под fix, если нельзя использовать let rec и and

2021-10-03 16:45 UTC, Kakadu commented
> 
> Пока что не понимаю как не копипастить функции под fix, если нельзя использовать let rec и and

Я не очень понимаю в чем именно проблема, но может вот это поможет? https://discuss.ocaml.org/t/mutually-recursive-parser-in-angstrom/6724/4?u=kakadu

2021-12-07 21:02 UTC, AndrewOleynikov commented
Я не понимаю, что он хочет. Локально opam exec -- dune build @fmt никак не ругается

2021-12-07 21:21 UTC, Kakadu commented
Попробуйте сравнить версию ocamlformat

2021-12-15 20:49 UTC, Kakadu commented on C/README.md
> +License: LGPL for implementation code + WTFPL for test examles in miniLanguage
Сделайте README соответсвующее

2021-12-15 21:47 UTC, Kakadu commented on C/lib/interpreterctx.ml
> +    b_srch' v @@ List.sort compare l
Это всё ещё здесь?

2021-12-15 21:48 UTC, Kakadu commented on C/lib/interpreterctx.ml
> +    | CT_ARRAY (size, tt) -> sizeof ctx tt >>= fun x -> return @@ (x * size)
Здесь не нужно @@ и в подобных местах тоже

2021-12-15 21:49 UTC, Kakadu commented on C/lib/interpreterctx.ml
> +        let ctx = ctx in
Зачем?

2021-12-15 22:10 UTC, Kakadu commented on C/lib/interpreterctx.ml
> +            | [ v ] -> (
Почему нельзя было помэтчить пару?

2021-12-15 22:22 UTC, Kakadu commented on C/lib/interpreterctx.ml
> +    | _ -> error "sig 6~~"
Это магические константы? Что они означают?

2021-12-15 22:29 UTC, Kakadu commented on C/lib/interpreterctx.ml
> +        >>= fun cs ->
Вам не кажется, что создавать значение, оборачиивать в монаду и затем сразу разворачивать байндом, чтобы заглянуть внутрь --- это слишком сложно?

2021-12-15 22:31 UTC, Kakadu commented on C/lib/interpreterctx.ml
> +            Hashtbl.remove cs.vars ".";
В набор введенных переменных попадает переменная с именем "точка"? Мне это не мерещится?

2021-12-15 23:24 UTC, AndrewOleynikov commented on C/lib/interpreterctx.ml
> +    b_srch' v @@ List.sort compare l
Это не эквивалент List.mem_assoc или речь о том, что это должно быть в отдельном файле, как утилита?

2021-12-15 23:24 UTC, AndrewOleynikov commented on C/lib/interpreterctx.ml
> +    | _ -> error "sig 6~~"
Это заглушки, куда интерпретатор не должен попадать

2021-12-16 16:20 UTC, AndrewOleynikov commented on C/lib/interpreterctx.ml
> +            Hashtbl.remove cs.vars ".";
Я забыл про эту часть - исправил

2021-12-16 16:40 UTC, AndrewOleynikov commented on C/lib/interpreterctx.ml
> +    b_srch' v @@ List.sort compare l
Вынес в отдельный файл

2021-12-16 17:42 UTC, Kakadu commented on C/lib/interpreterctx.ml
> +    b_srch' v @@ List.sort compare l
Запускать бинарный поиск на списке -- жутко неэффективно. Придумайте что-нибудь другое

2021-12-16 19:50 UTC, Kakadu commented on C/lib/interpreterctx.ml
> +    b_srch' v @@ List.sort compare l
Кстати, какова по Вашему асимптотическая сложность этого бинарного поиска?

2021-12-16 19:56 UTC, Kakadu commented on C/lib/interpreterctx.ml
> +    | _ -> error "sig 6~~"
По-хорошему, такого кода быть не должно, так как это магические константы. Сделайте получше.

2021-12-16 22:01 UTC, AndrewOleynikov commented on C/lib/interpreterctx.ml
> +    b_srch' v @@ List.sort compare l
n logn

2021-12-16 22:04 UTC, AndrewOleynikov commented on C/lib/interpreterctx.ml
> +    | _ -> error "sig 6~~"
Изменил

2021-12-16 22:04 UTC, AndrewOleynikov commented on C/lib/interpreterctx.ml
> +    b_srch' v @@ List.sort compare l
Поменял на линейный

2021-12-17 21:48 UTC, Kakadu commented on C/lib/interpreterctx.ml
> +    b_srch' v @@ List.sort compare l
Так лучше

2021-12-19 13:02 UTC, Kakadu commented on C/lib/interpreterctx.ml
> +type h_value = Vrval of string * v_value | Vdval of int * v_value
А в чем разница между этими двумя штуками? (допишите доку)

2021-12-19 13:04 UTC, Kakadu commented on C/lib/interpreterctx.ml
> +    | _ -> error "~CREATE_VAR~"
Из описания совершенно не понятно что пошло не так. Сделайте нормальное сообщение об ошибке

2021-12-19 13:07 UTC, Kakadu commented on C/lib/interpreterctx.ml
> +          List.fold_right (fun nt ts -> get_pair nt :: ts) args []
Напишите покороче. 
Да и приписывание типов, где они не нужны -- плохая практика.

2021-12-19 13:09 UTC, Kakadu commented on C/lib/interpreterctx.ml
> +            | CT_STRUCT n when n = name -> error "Recursive type error"
Если рекурсивный тип структуры не поддерживается, укажите это явно в README

2021-12-19 13:09 UTC, Kakadu commented on C/lib/interpreterctx.ml
> +            | CT_STRUCT n when n = name -> error "Recursive type error"
Правда я не очень понимаю как тогда получится список связный описать....

2021-12-19 16:00 UTC, Kakadu commented on C/lib/interpreterctx.ml
> +  | Vtype of types
Допишите доку к v_value. Я вот без идей, например, как значением может быть тип, описываемый с помощью Vtype

2021-12-19 17:01 UTC, Kakadu commented
````diff
diff --git a/C/demos/demoFree.ml b/C/demos/demoFree.ml
index 523c385..03f35a3 100644
--- a/C/demos/demoFree.ml
+++ b/C/demos/demoFree.ml
@@ -9,10 +9,15 @@ let test =
       #include <a.h>
 
       int main () {
-        
+
         int *arr0 = malloc(sizeof(int) * 5);
         int ans0 = arr0;
         free(arr0);
+        free(arr0);
+        free(arr0);
+        free(arr0);
+        free(arr0);
+        *arr0 = 1;
         int *arr1 = malloc(sizeof(int) * 5);
         int ans1 = arr1;
 
````

А почему вот это изменение на поведение Вашего интерпретатора не влияет?

2021-12-19 17:11 UTC, Kakadu commented
И почему без `#include <a.h>` всё ломается?

2021-12-21 13:48 UTC, AndrewOleynikov commented on C/lib/interpreterctx.ml
> +            | CT_STRUCT n when n = name -> error "Recursive type error"
В си нельзя объявлять структуры вида:   
struct A a { struct A field;  };

Связный список реализуется с помощью указателя на структуру

2021-12-21 13:51 UTC, AndrewOleynikov commented on C/lib/interpreterctx.ml
> +type h_value = Vrval of string * v_value | Vdval of int * v_value
Это элементы в куче или в таблице переменных. Первое для безымянных значений. 
Доку дополнил

2021-12-21 13:56 UTC, AndrewOleynikov commented on C/lib/interpreterctx.ml
> +    | _ -> error "~CREATE_VAR~"
Поменял сообщение об ошибке. Это один из мертвых случаев, в которые интерпретатор не попадает, будет ли лучше вместо ошибки ничего не делать (как id из алгебры)?

2021-12-21 13:56 UTC, AndrewOleynikov commented on C/lib/interpreterctx.ml
> +          List.fold_right (fun nt ts -> get_pair nt :: ts) args []
Убрал типы везде

2021-12-21 14:04 UTC, AndrewOleynikov commented
> 

Вы пораждаете неопределенное поведение. Могу сказать, что в дальнейшем, если продолжить делать что либо с этим кодом, то *arr0 в какой то момент не будет равен 1, потому что arr0 был освобожден. В настоящем си происходит что-то похожее
https://riptutorial.com/c/example/2775/read-value-of-pointer-that-was-freed

С двойным free() аналогично:
https://riptutorial.com/c/example/7223/freeing-memory-twice

2021-12-21 14:10 UTC, AndrewOleynikov commented
> И почему без `#include <a.h>` всё ломается?

Исправил. 
Записи вида #include... -- не более чем бесполезная запись

2021-12-22 20:29 UTC, Kakadu commented on C/lib/interpreterctx.ml
> +    | _ -> error "~CREATE_VAR~"
Нет, ничего не делать будет совсем плохо. Лучше сказать, что "not reachable", и объяснить почему. В идеале лучше переписать код, чтобы "not reachable" случай не случился.  Но я не могу подсказать как именно, потому что не очень понимаю что происходит.

2021-12-22 20:30 UTC, Kakadu commented
> Исправил.
> Запись вида #include... -- не более чем бесполезная запись

Если я от Вас не хотел инклуды, и они бесполезны, давайте их не будет в тестовых программах.

2021-12-22 20:32 UTC, Kakadu commented on C/README.md
> +  - Изменение значений большего типа меньшим
А меньшего большим значит можно? Есть ли на это демка?

2021-12-22 20:40 UTC, Kakadu commented
Ещё там есть куча гадости найденной линтером, исправьте её по максимуму

2021-12-23 17:48 UTC, Kakadu commented on C/lib/interpreterctx.ml
> +
Лучше используйте стандартный Format.asprintf

2021-12-23 17:49 UTC, Kakadu commented on C/lib/interpreterctx.ml
> +    if List.length args - List.length vals = 0 then (
Как Вы думаете, почему на прошлый код ругался линтер?

2021-12-23 18:43 UTC, Kakadu commented on C/lib/interpreterctx.ml
> +    if List.length args - List.length vals = 0 then (
Хотя, наверное, это ложное срабатывание

2021-12-23 18:46 UTC, AndrewOleynikov commented on C/README.md
> +  - Изменение значений большего типа меньшим
Изначально, я подумал, что это бесполезно реализовывать для случаев, где исход - нетривиальное приведение, потому что практического применения я не видел и легко попасть в неопределенное поведение.
Изменил и добавил тесты

2021-12-23 18:49 UTC, AndrewOleynikov commented on C/lib/interpreterctx.ml
> +
Скопипастил Ваше решение с форума

2021-12-23 18:50 UTC, AndrewOleynikov commented
> > Исправил.
> > Запись вида #include... -- не более чем бесполезная запись
> 
> Если я от Вас не хотел инклуды, и они бесполезны, давайте их не будет в тестовых программах.

Убрал из тестов

2021-12-23 18:51 UTC, AndrewOleynikov commented on C/lib/interpreterctx.ml
> +    | _ -> error "~CREATE_VAR~"
Поменял сообщения у всех таких случаев

2021-12-23 20:08 UTC, Kakadu commented on C/lib/interpreterctx.ml
>  let fmt_list fa fmt xs =
Там вроде есть `Format.pp_print_list`...

2021-12-23 20:09 UTC, Kakadu commented on C/lib/interpreterctx.ml
> +
Какого?

2021-12-23 20:11 UTC, AndrewOleynikov commented on C/lib/interpreterctx.ml
> +
Ну по мотивам
https://discuss.ocaml.org/t/need-help-with-formatting-lists/4204

2021-12-23 20:14 UTC, AndrewOleynikov commented on C/lib/interpreterctx.ml
>  let fmt_list fa fmt xs =
У  меня с этим как-то не сложилось, попробую разобраться

2021-12-23 21:08 UTC, AndrewOleynikov commented on C/lib/interpreterctx.ml
>  let fmt_list fa fmt xs =
Решил, что использовать тюплы будет удобнее

2021-12-24 20:36 UTC, Kakadu commented on C/lib/interpreterctx.ml
>  let fmt_list fa fmt xs =
Но сейчас же только "списки" трёх можно печатать. Это отстой.

2021-12-24 21:21 UTC, AndrewOleynikov commented on C/lib/interpreterctx.ml
>  let fmt_list fa fmt xs =
Сделал адекватно, без pp_mpt нельзя

2021-12-25 12:24 UTC, Kakadu approved these changes

2021-12-25 12:24 UTC, merged